// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin-item.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminItem struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32            `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId             uint32            `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CategoryId           uint32            `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Title                string            `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Article              string            `protobuf:"bytes,7,opt,name=article,proto3" json:"article,omitempty"`
	Alias                string            `protobuf:"bytes,8,opt,name=alias,proto3" json:"alias,omitempty"`
	Description          string            `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32           `protobuf:"fixed32,10,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice             float32           `protobuf:"fixed32,11,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	Count                int32             `protobuf:"varint,13,opt,name=count,proto3" json:"count,omitempty"`
	InStock              bool              `protobuf:"varint,14,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Disable              bool              `protobuf:"varint,15,opt,name=disable,proto3" json:"disable,omitempty"`
	Sort                 uint32            `protobuf:"varint,16,opt,name=sort,proto3" json:"sort,omitempty"`
	SeoTitle             string            `protobuf:"bytes,17,opt,name=seo_title,json=seoTitle,proto3" json:"seo_title,omitempty"`
	SeoDescription       string            `protobuf:"bytes,18,opt,name=seo_description,json=seoDescription,proto3" json:"seo_description,omitempty"`
	SeoKeywords          string            `protobuf:"bytes,19,opt,name=seo_keywords,json=seoKeywords,proto3" json:"seo_keywords,omitempty"`
	Vendor               *Vendor           `protobuf:"bytes,20,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Currency             *Currency         `protobuf:"bytes,21,opt,name=currency,proto3" json:"currency,omitempty"`
	Images               []*AdminItemImage `protobuf:"bytes,22,rep,name=images,proto3" json:"images,omitempty"`
	Offers               []*AdminItem      `protobuf:"bytes,23,rep,name=offers,proto3" json:"offers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AdminItem) Reset()         { *m = AdminItem{} }
func (m *AdminItem) String() string { return proto.CompactTextString(m) }
func (*AdminItem) ProtoMessage()    {}
func (*AdminItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{0}
}

func (m *AdminItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminItem.Unmarshal(m, b)
}
func (m *AdminItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminItem.Marshal(b, m, deterministic)
}
func (m *AdminItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminItem.Merge(m, src)
}
func (m *AdminItem) XXX_Size() int {
	return xxx_messageInfo_AdminItem.Size(m)
}
func (m *AdminItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminItem.DiscardUnknown(m)
}

var xxx_messageInfo_AdminItem proto.InternalMessageInfo

func (m *AdminItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AdminItem) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AdminItem) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *AdminItem) GetCategoryId() uint32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *AdminItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AdminItem) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *AdminItem) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *AdminItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AdminItem) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AdminItem) GetOldPrice() float32 {
	if m != nil {
		return m.OldPrice
	}
	return 0
}

func (m *AdminItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *AdminItem) GetInStock() bool {
	if m != nil {
		return m.InStock
	}
	return false
}

func (m *AdminItem) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

func (m *AdminItem) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *AdminItem) GetSeoTitle() string {
	if m != nil {
		return m.SeoTitle
	}
	return ""
}

func (m *AdminItem) GetSeoDescription() string {
	if m != nil {
		return m.SeoDescription
	}
	return ""
}

func (m *AdminItem) GetSeoKeywords() string {
	if m != nil {
		return m.SeoKeywords
	}
	return ""
}

func (m *AdminItem) GetVendor() *Vendor {
	if m != nil {
		return m.Vendor
	}
	return nil
}

func (m *AdminItem) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *AdminItem) GetImages() []*AdminItemImage {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *AdminItem) GetOffers() []*AdminItem {
	if m != nil {
		return m.Offers
	}
	return nil
}

type AdminItemImage struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               uint32   `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Filename             string   `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Sort                 uint32   `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	PropertyValueId      uint32   `protobuf:"varint,6,opt,name=property_value_id,json=propertyValueId,proto3" json:"property_value_id,omitempty"`
	Main                 bool     `protobuf:"varint,7,opt,name=main,proto3" json:"main,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminItemImage) Reset()         { *m = AdminItemImage{} }
func (m *AdminItemImage) String() string { return proto.CompactTextString(m) }
func (*AdminItemImage) ProtoMessage()    {}
func (*AdminItemImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{1}
}

func (m *AdminItemImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminItemImage.Unmarshal(m, b)
}
func (m *AdminItemImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminItemImage.Marshal(b, m, deterministic)
}
func (m *AdminItemImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminItemImage.Merge(m, src)
}
func (m *AdminItemImage) XXX_Size() int {
	return xxx_messageInfo_AdminItemImage.Size(m)
}
func (m *AdminItemImage) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminItemImage.DiscardUnknown(m)
}

var xxx_messageInfo_AdminItemImage proto.InternalMessageInfo

func (m *AdminItemImage) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdminItemImage) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AdminItemImage) GetItemId() uint32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *AdminItemImage) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *AdminItemImage) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *AdminItemImage) GetPropertyValueId() uint32 {
	if m != nil {
		return m.PropertyValueId
	}
	return 0
}

func (m *AdminItemImage) GetMain() bool {
	if m != nil {
		return m.Main
	}
	return false
}

type AdminItemProperty struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	PropertyValueIds     []uint32 `protobuf:"varint,2,rep,packed,name=property_value_ids,json=propertyValueIds,proto3" json:"property_value_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminItemProperty) Reset()         { *m = AdminItemProperty{} }
func (m *AdminItemProperty) String() string { return proto.CompactTextString(m) }
func (*AdminItemProperty) ProtoMessage()    {}
func (*AdminItemProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{2}
}

func (m *AdminItemProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminItemProperty.Unmarshal(m, b)
}
func (m *AdminItemProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminItemProperty.Marshal(b, m, deterministic)
}
func (m *AdminItemProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminItemProperty.Merge(m, src)
}
func (m *AdminItemProperty) XXX_Size() int {
	return xxx_messageInfo_AdminItemProperty.Size(m)
}
func (m *AdminItemProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminItemProperty.DiscardUnknown(m)
}

var xxx_messageInfo_AdminItemProperty proto.InternalMessageInfo

func (m *AdminItemProperty) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AdminItemProperty) GetPropertyValueIds() []uint32 {
	if m != nil {
		return m.PropertyValueIds
	}
	return nil
}

type AdminItemRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminItemRequest) Reset()         { *m = AdminItemRequest{} }
func (m *AdminItemRequest) String() string { return proto.CompactTextString(m) }
func (*AdminItemRequest) ProtoMessage()    {}
func (*AdminItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{3}
}

func (m *AdminItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminItemRequest.Unmarshal(m, b)
}
func (m *AdminItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminItemRequest.Marshal(b, m, deterministic)
}
func (m *AdminItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminItemRequest.Merge(m, src)
}
func (m *AdminItemRequest) XXX_Size() int {
	return xxx_messageInfo_AdminItemRequest.Size(m)
}
func (m *AdminItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminItemRequest proto.InternalMessageInfo

func (m *AdminItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AdminDraftRequest struct {
	ParentId             uint32   `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminDraftRequest) Reset()         { *m = AdminDraftRequest{} }
func (m *AdminDraftRequest) String() string { return proto.CompactTextString(m) }
func (*AdminDraftRequest) ProtoMessage()    {}
func (*AdminDraftRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{4}
}

func (m *AdminDraftRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminDraftRequest.Unmarshal(m, b)
}
func (m *AdminDraftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminDraftRequest.Marshal(b, m, deterministic)
}
func (m *AdminDraftRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminDraftRequest.Merge(m, src)
}
func (m *AdminDraftRequest) XXX_Size() int {
	return xxx_messageInfo_AdminDraftRequest.Size(m)
}
func (m *AdminDraftRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminDraftRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminDraftRequest proto.InternalMessageInfo

func (m *AdminDraftRequest) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type AdminItemsRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminItemsRequest) Reset()         { *m = AdminItemsRequest{} }
func (m *AdminItemsRequest) String() string { return proto.CompactTextString(m) }
func (*AdminItemsRequest) ProtoMessage()    {}
func (*AdminItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{5}
}

func (m *AdminItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminItemsRequest.Unmarshal(m, b)
}
func (m *AdminItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminItemsRequest.Marshal(b, m, deterministic)
}
func (m *AdminItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminItemsRequest.Merge(m, src)
}
func (m *AdminItemsRequest) XXX_Size() int {
	return xxx_messageInfo_AdminItemsRequest.Size(m)
}
func (m *AdminItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminItemsRequest proto.InternalMessageInfo

func (m *AdminItemsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AdminItemsRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *AdminItemsRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *AdminItemsRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type AdminOffersRequest struct {
	ItemId               uint32   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminOffersRequest) Reset()         { *m = AdminOffersRequest{} }
func (m *AdminOffersRequest) String() string { return proto.CompactTextString(m) }
func (*AdminOffersRequest) ProtoMessage()    {}
func (*AdminOffersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{6}
}

func (m *AdminOffersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminOffersRequest.Unmarshal(m, b)
}
func (m *AdminOffersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminOffersRequest.Marshal(b, m, deterministic)
}
func (m *AdminOffersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminOffersRequest.Merge(m, src)
}
func (m *AdminOffersRequest) XXX_Size() int {
	return xxx_messageInfo_AdminOffersRequest.Size(m)
}
func (m *AdminOffersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminOffersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminOffersRequest proto.InternalMessageInfo

func (m *AdminOffersRequest) GetItemId() uint32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *AdminOffersRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AdminOffersRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *AdminOffersRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *AdminOffersRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type AdminEditItemRequest struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             uint32               `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Article              string               `protobuf:"bytes,4,opt,name=article,proto3" json:"article,omitempty"`
	Alias                string               `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	Count                int32                `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	InStock              bool                 `protobuf:"varint,7,opt,name=inStock,proto3" json:"inStock,omitempty"`
	Description          string               `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32              `protobuf:"fixed32,9,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice             float32              `protobuf:"fixed32,10,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	CurrencyId           uint32               `protobuf:"varint,11,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Disable              bool                 `protobuf:"varint,12,opt,name=disable,proto3" json:"disable,omitempty"`
	Sort                 uint32               `protobuf:"varint,13,opt,name=sort,proto3" json:"sort,omitempty"`
	VendorId             uint32               `protobuf:"varint,14,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ItemImages           []uint32             `protobuf:"varint,15,rep,packed,name=item_images,json=itemImages,proto3" json:"item_images,omitempty"`
	UploadImages         []uint32             `protobuf:"varint,16,rep,packed,name=upload_images,json=uploadImages,proto3" json:"upload_images,omitempty"`
	Properties           []*AdminItemProperty `protobuf:"bytes,17,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AdminEditItemRequest) Reset()         { *m = AdminEditItemRequest{} }
func (m *AdminEditItemRequest) String() string { return proto.CompactTextString(m) }
func (*AdminEditItemRequest) ProtoMessage()    {}
func (*AdminEditItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{7}
}

func (m *AdminEditItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminEditItemRequest.Unmarshal(m, b)
}
func (m *AdminEditItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminEditItemRequest.Marshal(b, m, deterministic)
}
func (m *AdminEditItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminEditItemRequest.Merge(m, src)
}
func (m *AdminEditItemRequest) XXX_Size() int {
	return xxx_messageInfo_AdminEditItemRequest.Size(m)
}
func (m *AdminEditItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminEditItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminEditItemRequest proto.InternalMessageInfo

func (m *AdminEditItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdminEditItemRequest) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *AdminEditItemRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AdminEditItemRequest) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *AdminEditItemRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *AdminEditItemRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *AdminEditItemRequest) GetInStock() bool {
	if m != nil {
		return m.InStock
	}
	return false
}

func (m *AdminEditItemRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AdminEditItemRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AdminEditItemRequest) GetOldPrice() float32 {
	if m != nil {
		return m.OldPrice
	}
	return 0
}

func (m *AdminEditItemRequest) GetCurrencyId() uint32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *AdminEditItemRequest) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

func (m *AdminEditItemRequest) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *AdminEditItemRequest) GetVendorId() uint32 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *AdminEditItemRequest) GetItemImages() []uint32 {
	if m != nil {
		return m.ItemImages
	}
	return nil
}

func (m *AdminEditItemRequest) GetUploadImages() []uint32 {
	if m != nil {
		return m.UploadImages
	}
	return nil
}

func (m *AdminEditItemRequest) GetProperties() []*AdminItemProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

type AdminDeleteItemRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminDeleteItemRequest) Reset()         { *m = AdminDeleteItemRequest{} }
func (m *AdminDeleteItemRequest) String() string { return proto.CompactTextString(m) }
func (*AdminDeleteItemRequest) ProtoMessage()    {}
func (*AdminDeleteItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{8}
}

func (m *AdminDeleteItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminDeleteItemRequest.Unmarshal(m, b)
}
func (m *AdminDeleteItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminDeleteItemRequest.Marshal(b, m, deterministic)
}
func (m *AdminDeleteItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminDeleteItemRequest.Merge(m, src)
}
func (m *AdminDeleteItemRequest) XXX_Size() int {
	return xxx_messageInfo_AdminDeleteItemRequest.Size(m)
}
func (m *AdminDeleteItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminDeleteItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminDeleteItemRequest proto.InternalMessageInfo

func (m *AdminDeleteItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdminDeleteItemRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AdminDeleteItemRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *AdminDeleteItemRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *AdminDeleteItemRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type AdminDeleteOfferRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             uint32   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminDeleteOfferRequest) Reset()         { *m = AdminDeleteOfferRequest{} }
func (m *AdminDeleteOfferRequest) String() string { return proto.CompactTextString(m) }
func (*AdminDeleteOfferRequest) ProtoMessage()    {}
func (*AdminDeleteOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{9}
}

func (m *AdminDeleteOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminDeleteOfferRequest.Unmarshal(m, b)
}
func (m *AdminDeleteOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminDeleteOfferRequest.Marshal(b, m, deterministic)
}
func (m *AdminDeleteOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminDeleteOfferRequest.Merge(m, src)
}
func (m *AdminDeleteOfferRequest) XXX_Size() int {
	return xxx_messageInfo_AdminDeleteOfferRequest.Size(m)
}
func (m *AdminDeleteOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminDeleteOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminDeleteOfferRequest proto.InternalMessageInfo

func (m *AdminDeleteOfferRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdminDeleteOfferRequest) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *AdminDeleteOfferRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AdminDeleteOfferRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *AdminDeleteOfferRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *AdminDeleteOfferRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type AdminItemBindRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId           string   `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminItemBindRequest) Reset()         { *m = AdminItemBindRequest{} }
func (m *AdminItemBindRequest) String() string { return proto.CompactTextString(m) }
func (*AdminItemBindRequest) ProtoMessage()    {}
func (*AdminItemBindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{10}
}

func (m *AdminItemBindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminItemBindRequest.Unmarshal(m, b)
}
func (m *AdminItemBindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminItemBindRequest.Marshal(b, m, deterministic)
}
func (m *AdminItemBindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminItemBindRequest.Merge(m, src)
}
func (m *AdminItemBindRequest) XXX_Size() int {
	return xxx_messageInfo_AdminItemBindRequest.Size(m)
}
func (m *AdminItemBindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminItemBindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminItemBindRequest proto.InternalMessageInfo

func (m *AdminItemBindRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdminItemBindRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

type AdminUploadOfferRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Article              string   `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	ParentId             uint32   `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CategoryId           uint32   `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Currency             string   `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Count                int32    `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	InStock              bool     `protobuf:"varint,8,opt,name=inStock,proto3" json:"inStock,omitempty"`
	Description          string   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Vendor               string   `protobuf:"bytes,10,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Country              string   `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	Images               []string `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	Properties           []uint32 `protobuf:"varint,13,rep,packed,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUploadOfferRequest) Reset()         { *m = AdminUploadOfferRequest{} }
func (m *AdminUploadOfferRequest) String() string { return proto.CompactTextString(m) }
func (*AdminUploadOfferRequest) ProtoMessage()    {}
func (*AdminUploadOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{11}
}

func (m *AdminUploadOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUploadOfferRequest.Unmarshal(m, b)
}
func (m *AdminUploadOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUploadOfferRequest.Marshal(b, m, deterministic)
}
func (m *AdminUploadOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUploadOfferRequest.Merge(m, src)
}
func (m *AdminUploadOfferRequest) XXX_Size() int {
	return xxx_messageInfo_AdminUploadOfferRequest.Size(m)
}
func (m *AdminUploadOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUploadOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUploadOfferRequest proto.InternalMessageInfo

func (m *AdminUploadOfferRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AdminUploadOfferRequest) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *AdminUploadOfferRequest) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *AdminUploadOfferRequest) GetCategoryId() uint32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *AdminUploadOfferRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AdminUploadOfferRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *AdminUploadOfferRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *AdminUploadOfferRequest) GetInStock() bool {
	if m != nil {
		return m.InStock
	}
	return false
}

func (m *AdminUploadOfferRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AdminUploadOfferRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *AdminUploadOfferRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AdminUploadOfferRequest) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *AdminUploadOfferRequest) GetProperties() []uint32 {
	if m != nil {
		return m.Properties
	}
	return nil
}

type AdminItemResponse struct {
	Item                 *AdminItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AdminItemResponse) Reset()         { *m = AdminItemResponse{} }
func (m *AdminItemResponse) String() string { return proto.CompactTextString(m) }
func (*AdminItemResponse) ProtoMessage()    {}
func (*AdminItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{12}
}

func (m *AdminItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminItemResponse.Unmarshal(m, b)
}
func (m *AdminItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminItemResponse.Marshal(b, m, deterministic)
}
func (m *AdminItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminItemResponse.Merge(m, src)
}
func (m *AdminItemResponse) XXX_Size() int {
	return xxx_messageInfo_AdminItemResponse.Size(m)
}
func (m *AdminItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminItemResponse proto.InternalMessageInfo

func (m *AdminItemResponse) GetItem() *AdminItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type AdminItemsResponse struct {
	Items                []*AdminItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total                uint32       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AdminItemsResponse) Reset()         { *m = AdminItemsResponse{} }
func (m *AdminItemsResponse) String() string { return proto.CompactTextString(m) }
func (*AdminItemsResponse) ProtoMessage()    {}
func (*AdminItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{13}
}

func (m *AdminItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminItemsResponse.Unmarshal(m, b)
}
func (m *AdminItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminItemsResponse.Marshal(b, m, deterministic)
}
func (m *AdminItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminItemsResponse.Merge(m, src)
}
func (m *AdminItemsResponse) XXX_Size() int {
	return xxx_messageInfo_AdminItemsResponse.Size(m)
}
func (m *AdminItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminItemsResponse proto.InternalMessageInfo

func (m *AdminItemsResponse) GetItems() []*AdminItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *AdminItemsResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AdminOffersResponse struct {
	Offers               []*AdminItem `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	Total                uint32       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AdminOffersResponse) Reset()         { *m = AdminOffersResponse{} }
func (m *AdminOffersResponse) String() string { return proto.CompactTextString(m) }
func (*AdminOffersResponse) ProtoMessage()    {}
func (*AdminOffersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{14}
}

func (m *AdminOffersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminOffersResponse.Unmarshal(m, b)
}
func (m *AdminOffersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminOffersResponse.Marshal(b, m, deterministic)
}
func (m *AdminOffersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminOffersResponse.Merge(m, src)
}
func (m *AdminOffersResponse) XXX_Size() int {
	return xxx_messageInfo_AdminOffersResponse.Size(m)
}
func (m *AdminOffersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminOffersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminOffersResponse proto.InternalMessageInfo

func (m *AdminOffersResponse) GetOffers() []*AdminItem {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *AdminOffersResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AdminItemImagesResponse struct {
	Images               []*AdminItemImage `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AdminItemImagesResponse) Reset()         { *m = AdminItemImagesResponse{} }
func (m *AdminItemImagesResponse) String() string { return proto.CompactTextString(m) }
func (*AdminItemImagesResponse) ProtoMessage()    {}
func (*AdminItemImagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ad94a9dd9ea674f, []int{15}
}

func (m *AdminItemImagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminItemImagesResponse.Unmarshal(m, b)
}
func (m *AdminItemImagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminItemImagesResponse.Marshal(b, m, deterministic)
}
func (m *AdminItemImagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminItemImagesResponse.Merge(m, src)
}
func (m *AdminItemImagesResponse) XXX_Size() int {
	return xxx_messageInfo_AdminItemImagesResponse.Size(m)
}
func (m *AdminItemImagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminItemImagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminItemImagesResponse proto.InternalMessageInfo

func (m *AdminItemImagesResponse) GetImages() []*AdminItemImage {
	if m != nil {
		return m.Images
	}
	return nil
}

func init() {
	proto.RegisterType((*AdminItem)(nil), "v1.AdminItem")
	proto.RegisterType((*AdminItemImage)(nil), "v1.AdminItemImage")
	proto.RegisterType((*AdminItemProperty)(nil), "v1.AdminItemProperty")
	proto.RegisterType((*AdminItemRequest)(nil), "v1.AdminItemRequest")
	proto.RegisterType((*AdminDraftRequest)(nil), "v1.AdminDraftRequest")
	proto.RegisterType((*AdminItemsRequest)(nil), "v1.AdminItemsRequest")
	proto.RegisterType((*AdminOffersRequest)(nil), "v1.AdminOffersRequest")
	proto.RegisterType((*AdminEditItemRequest)(nil), "v1.AdminEditItemRequest")
	proto.RegisterType((*AdminDeleteItemRequest)(nil), "v1.AdminDeleteItemRequest")
	proto.RegisterType((*AdminDeleteOfferRequest)(nil), "v1.AdminDeleteOfferRequest")
	proto.RegisterType((*AdminItemBindRequest)(nil), "v1.AdminItemBindRequest")
	proto.RegisterType((*AdminUploadOfferRequest)(nil), "v1.AdminUploadOfferRequest")
	proto.RegisterType((*AdminItemResponse)(nil), "v1.AdminItemResponse")
	proto.RegisterType((*AdminItemsResponse)(nil), "v1.AdminItemsResponse")
	proto.RegisterType((*AdminOffersResponse)(nil), "v1.AdminOffersResponse")
	proto.RegisterType((*AdminItemImagesResponse)(nil), "v1.AdminItemImagesResponse")
}

func init() {
	proto.RegisterFile("admin-item.proto", fileDescriptor_2ad94a9dd9ea674f)
}

var fileDescriptor_2ad94a9dd9ea674f = []byte{
	// 1270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x97, 0x9d, 0x7f, 0xce, 0xe4, 0x4f, 0xdb, 0xbd, 0x34, 0x5d, 0x52, 0x04, 0x39, 0x9f, 0x10,
	0xd1, 0x09, 0x72, 0x5c, 0x11, 0x08, 0x89, 0x17, 0xb8, 0xb6, 0x1c, 0xd1, 0x49, 0x5c, 0xe5, 0xd2,
	0x7b, 0x8d, 0xdc, 0x78, 0x1b, 0xad, 0xce, 0xf1, 0x06, 0xaf, 0x13, 0xd4, 0xfb, 0x0a, 0xbc, 0xf0,
	0x35, 0x78, 0xe4, 0x2b, 0xf0, 0x9d, 0x80, 0x57, 0xb4, 0x7f, 0x6c, 0xaf, 0xdd, 0x3a, 0x95, 0x10,
	0xe2, 0xcd, 0x3b, 0x33, 0x3b, 0x3b, 0x3b, 0x33, 0xbf, 0xdf, 0xac, 0x61, 0xdf, 0x0f, 0x56, 0x34,
	0xfa, 0x94, 0x26, 0x64, 0x35, 0x5d, 0xc7, 0x2c, 0x61, 0xc8, 0xde, 0x3e, 0x1f, 0x1d, 0x2f, 0x19,
	0x5b, 0x86, 0xe4, 0x99, 0x94, 0x5c, 0x6f, 0x6e, 0x9e, 0x91, 0xd5, 0x3a, 0xb9, 0x55, 0x06, 0xa3,
	0x81, 0xda, 0xb2, 0xf0, 0x13, 0xb2, 0x64, 0x71, 0x49, 0xba, 0x8e, 0xd9, 0x9a, 0xc4, 0x99, 0x6d,
	0x77, 0x4b, 0xa2, 0x80, 0xc5, 0x7a, 0xd5, 0x5f, 0x6c, 0xe2, 0x98, 0x44, 0x0b, 0xad, 0x75, 0xff,
	0xaa, 0x43, 0xfb, 0x5b, 0xb1, 0x6d, 0x96, 0x90, 0x15, 0xea, 0x83, 0x4d, 0x03, 0x6c, 0x8d, 0xad,
	0x49, 0xdb, 0xb3, 0x69, 0x80, 0x8e, 0xa0, 0xb5, 0xe1, 0x24, 0x9e, 0xd3, 0x00, 0xdb, 0x63, 0x6b,
	0xd2, 0xf3, 0x9a, 0x62, 0x39, 0x0b, 0xd0, 0x31, 0xb4, 0xd7, 0x7e, 0x4c, 0xa2, 0x44, 0xa8, 0xea,
	0x52, 0xe5, 0x28, 0xc1, 0x2c, 0x40, 0x1f, 0x42, 0x27, 0x8d, 0x4c, 0xa8, 0x1b, 0x52, 0x0d, 0xa9,
	0x68, 0x16, 0xa0, 0x01, 0x34, 0x12, 0x9a, 0x84, 0x04, 0x37, 0xe5, 0x49, 0x6a, 0x81, 0x30, 0xb4,
	0xfc, 0x38, 0xa1, 0x8b, 0x90, 0xe0, 0x96, 0x94, 0xa7, 0x4b, 0x61, 0xef, 0x87, 0xd4, 0xe7, 0xd8,
	0x51, 0xf6, 0x72, 0x81, 0xc6, 0xd0, 0x09, 0x08, 0x5f, 0xc4, 0x74, 0x9d, 0x50, 0x16, 0xe1, 0xb6,
	0xd4, 0x99, 0x22, 0xb1, 0x6f, 0x1d, 0xd3, 0x05, 0xc1, 0x30, 0xb6, 0x26, 0xb6, 0xa7, 0x16, 0x22,
	0x76, 0x16, 0x06, 0x73, 0xa5, 0xe9, 0x48, 0x8d, 0xc3, 0xc2, 0xe0, 0x42, 0x2a, 0x07, 0xd0, 0x58,
	0xb0, 0x4d, 0x94, 0xe0, 0xde, 0xd8, 0x9a, 0x34, 0x3c, 0xb5, 0x40, 0xef, 0x81, 0x43, 0xa3, 0x39,
	0x4f, 0xd8, 0xe2, 0x2d, 0xee, 0x8f, 0xad, 0x89, 0xe3, 0xb5, 0x68, 0x74, 0x29, 0x96, 0x22, 0xea,
	0x80, 0x72, 0xff, 0x3a, 0x24, 0x78, 0x4f, 0x69, 0xf4, 0x12, 0x21, 0xa8, 0x73, 0x16, 0x27, 0x78,
	0x5f, 0xde, 0x5f, 0x7e, 0x8b, 0xb3, 0x39, 0x61, 0x73, 0x75, 0xfb, 0x03, 0x19, 0xb1, 0xc3, 0x09,
	0xfb, 0x51, 0x26, 0xe0, 0x63, 0xd8, 0x13, 0x4a, 0xf3, 0x52, 0x48, 0x9a, 0xf4, 0x39, 0x61, 0x67,
	0xc6, 0xbd, 0x1e, 0x43, 0x57, 0x18, 0xbe, 0x25, 0xb7, 0x3f, 0xb3, 0x38, 0xe0, 0xf8, 0x91, 0xba,
	0x3a, 0x27, 0xec, 0x95, 0x16, 0x21, 0x17, 0x9a, 0xaa, 0xee, 0x78, 0x30, 0xb6, 0x26, 0x9d, 0x13,
	0x98, 0x6e, 0x9f, 0x4f, 0xdf, 0x48, 0x89, 0xa7, 0x35, 0x68, 0x02, 0x4e, 0xda, 0x0d, 0xf8, 0x50,
	0x5a, 0x75, 0x85, 0xd5, 0xa9, 0x96, 0x79, 0x99, 0x16, 0x3d, 0x85, 0x26, 0x5d, 0xf9, 0x4b, 0xc2,
	0xf1, 0x70, 0x5c, 0x9b, 0x74, 0x4e, 0x90, 0xb0, 0xcb, 0xda, 0x66, 0x26, 0x54, 0x9e, 0xb6, 0x40,
	0x1f, 0x41, 0x93, 0xdd, 0xdc, 0x90, 0x98, 0xe3, 0x23, 0x69, 0xdb, 0x2b, 0xd8, 0x7a, 0x5a, 0xe9,
	0xfe, 0x61, 0x41, 0xbf, 0xe8, 0xc1, 0xe8, 0xbe, 0xde, 0xee, 0xee, 0x3b, 0x82, 0x96, 0x40, 0x8b,
	0x50, 0xd4, 0x94, 0x42, 0x2c, 0x67, 0x01, 0x1a, 0x81, 0x73, 0x43, 0x43, 0x12, 0xf9, 0x2b, 0x22,
	0xbb, 0xb2, 0xed, 0x65, 0xeb, 0xac, 0x1c, 0x0d, 0xa3, 0x1c, 0x4f, 0xe1, 0x20, 0x45, 0xcb, 0x7c,
	0xeb, 0x87, 0x1b, 0x22, 0x5c, 0x36, 0xa5, 0xc1, 0x5e, 0xaa, 0x78, 0x23, 0xe4, 0xb3, 0x40, 0xec,
	0x5f, 0xf9, 0x34, 0x92, 0xbd, 0xe9, 0x78, 0xf2, 0xdb, 0xbd, 0x82, 0x83, 0xec, 0x0e, 0x17, 0xda,
	0x5e, 0x18, 0x2e, 0x58, 0x40, 0x34, 0x8c, 0xe4, 0x37, 0xfa, 0x04, 0xd0, 0x9d, 0x83, 0x38, 0xb6,
	0xc7, 0xb5, 0x49, 0xcf, 0xdb, 0x2f, 0x9d, 0xc4, 0x5d, 0x17, 0xf6, 0xf3, 0x84, 0x91, 0x9f, 0x36,
	0x84, 0x27, 0xe5, 0xe4, 0xb8, 0x9f, 0xe9, 0xa3, 0xcf, 0x62, 0xff, 0x26, 0x49, 0x8d, 0x0a, 0xb0,
	0xb4, 0x8a, 0xb0, 0x74, 0xb7, 0x46, 0xb0, 0x3c, 0xdd, 0x81, 0xa0, 0xbe, 0xf6, 0x97, 0x44, 0x1b,
	0xcb, 0x6f, 0xe5, 0x65, 0x49, 0xe6, 0x9c, 0xbe, 0x23, 0x3a, 0xf3, 0x8e, 0x10, 0x5c, 0xd2, 0x77,
	0x79, 0x1a, 0x6b, 0xea, 0x76, 0x32, 0x8d, 0xef, 0x43, 0x3b, 0xa0, 0x31, 0x59, 0xc8, 0x96, 0x55,
	0x79, 0xcf, 0x05, 0xee, 0xaf, 0x16, 0x20, 0x79, 0xf0, 0x6b, 0x59, 0xf9, 0xf4, 0x64, 0xa3, 0x88,
	0x56, 0xa1, 0x88, 0x69, 0x48, 0x76, 0x55, 0x48, 0xb5, 0x8a, 0x90, 0xea, 0x55, 0x21, 0x35, 0xca,
	0x21, 0xfd, 0x5d, 0x83, 0x81, 0x0c, 0xe9, 0x3c, 0xa0, 0xc9, 0x8e, 0x2c, 0x17, 0x13, 0x6a, 0x97,
	0x78, 0x2e, 0xa3, 0xb1, 0x5a, 0x05, 0x8d, 0xd5, 0x2b, 0x68, 0xac, 0x61, 0xd2, 0x58, 0xc6, 0x38,
	0x4d, 0x93, 0x71, 0x30, 0xa4, 0x0c, 0xa3, 0x1b, 0x2e, 0x23, 0x9c, 0x12, 0xed, 0x39, 0x3b, 0x68,
	0xaf, 0x5d, 0x49, 0x7b, 0x50, 0xa2, 0x3d, 0x41, 0xd9, 0x1a, 0xec, 0xe2, 0xa6, 0x1d, 0x4d, 0xd9,
	0x5a, 0x34, 0x0b, 0x4c, 0x9a, 0xeb, 0xde, 0x4f, 0x73, 0xbd, 0x22, 0xcd, 0x29, 0x8e, 0x11, 0xce,
	0xfa, 0x2a, 0x6d, 0x4a, 0xa0, 0xc6, 0x83, 0x2a, 0xbc, 0x62, 0x94, 0x3d, 0x09, 0x02, 0xa0, 0x29,
	0x0d, 0x70, 0xf4, 0x04, 0x7a, 0x9b, 0x75, 0xc8, 0xfc, 0x20, 0x35, 0xd9, 0x97, 0x26, 0x5d, 0x25,
	0xd4, 0x46, 0x5f, 0x00, 0x68, 0xdc, 0x50, 0xc2, 0xf1, 0x81, 0xa4, 0x9a, 0xc3, 0x02, 0xd5, 0xa4,
	0x80, 0xf4, 0x0c, 0x43, 0xf7, 0x17, 0x0b, 0x86, 0x0a, 0x37, 0x24, 0x24, 0x09, 0xd9, 0x55, 0xfb,
	0xff, 0xa1, 0x0f, 0x7f, 0xb3, 0xe0, 0xc8, 0x88, 0x46, 0x02, 0xe4, 0x5f, 0xb5, 0x62, 0x1a, 0x6b,
	0xad, 0x2a, 0xd6, 0x7a, 0x45, 0xac, 0x8d, 0xaa, 0x58, 0x9b, 0xe5, 0x58, 0x5f, 0x6a, 0xc8, 0x88,
	0x94, 0xbd, 0xa0, 0x51, 0x50, 0x15, 0x67, 0x69, 0xfa, 0xdb, 0xd2, 0x8f, 0x31, 0xfd, 0xdd, 0x3f,
	0x6d, 0x7d, 0xe9, 0x2b, 0x59, 0xcf, 0xc2, 0xa5, 0x33, 0x48, 0x59, 0x15, 0x90, 0xb2, 0x8b, 0x90,
	0x2a, 0x24, 0xa5, 0xb6, 0xfb, 0x1d, 0x52, 0xbf, 0xef, 0x1d, 0xa2, 0xe0, 0xd0, 0x30, 0x81, 0x32,
	0x32, 0xc6, 0xa2, 0xca, 0x42, 0x3e, 0x08, 0x33, 0xb0, 0xb6, 0x2a, 0xc0, 0xea, 0xec, 0x04, 0xeb,
	0x3d, 0x6f, 0x94, 0x61, 0x36, 0xa8, 0x41, 0x2a, 0xd3, 0xe1, 0x8c, 0xa1, 0x25, 0x9d, 0xc7, 0xb7,
	0x12, 0x8d, 0x6d, 0x2f, 0x5d, 0x8a, 0x1d, 0x1a, 0x17, 0xdd, 0x71, 0x4d, 0xec, 0xd0, 0x83, 0xf7,
	0x83, 0x02, 0x22, 0x7a, 0x0a, 0x56, 0x46, 0xeb, 0x7f, 0x69, 0xf0, 0xbf, 0x47, 0xf8, 0x9a, 0x45,
	0x9c, 0xa0, 0xc7, 0x50, 0x17, 0xc8, 0x93, 0xf9, 0xbe, 0x33, 0xab, 0xa5, 0xca, 0x7d, 0xad, 0xe9,
	0x5b, 0xcf, 0x0d, 0xbd, 0xf1, 0x09, 0x34, 0x84, 0x96, 0x63, 0xeb, 0xbe, 0x29, 0xaf, 0x74, 0xb2,
	0x9c, 0x2c, 0xf1, 0x43, 0xdd, 0xaf, 0x6a, 0xe1, 0x7a, 0xf0, 0xa8, 0x30, 0x0f, 0xb4, 0xc7, 0xfc,
	0xe1, 0x60, 0xed, 0x78, 0x38, 0x54, 0xf8, 0x3c, 0xd7, 0x3d, 0x95, 0xbd, 0x26, 0x72, 0xbf, 0xf9,
	0xe3, 0xc5, 0x7a, 0xe8, 0xf1, 0x72, 0xf2, 0x7b, 0xcb, 0x18, 0xbd, 0x97, 0x24, 0xde, 0x8a, 0x86,
	0xf8, 0xca, 0x7c, 0x22, 0x0f, 0x8a, 0x51, 0xa9, 0xbe, 0x1d, 0x1d, 0x96, 0xa4, 0xfa, 0xe8, 0x33,
	0x8d, 0x99, 0xd3, 0x98, 0xf8, 0x09, 0x91, 0xa3, 0x5a, 0x3a, 0xc9, 0xcd, 0xcd, 0xf1, 0x5d, 0xe5,
	0xe5, 0x1b, 0xe8, 0x15, 0x86, 0x15, 0xc2, 0x99, 0x5d, 0x69, 0x7e, 0x55, 0x79, 0x38, 0x87, 0xbd,
	0x12, 0xe9, 0xa1, 0x51, 0x1e, 0x42, 0x99, 0x09, 0x47, 0xc3, 0x82, 0x97, 0x3c, 0x93, 0xdf, 0xeb,
	0xe4, 0x18, 0x6c, 0x85, 0x8e, 0x4b, 0x7e, 0x4c, 0x38, 0x8f, 0x8e, 0x32, 0x65, 0xa9, 0xd6, 0x5f,
	0x03, 0xe4, 0xfe, 0xd1, 0x61, 0xf9, 0xbc, 0xdd, 0x61, 0xbc, 0xd2, 0x59, 0x7d, 0x49, 0x92, 0x2b,
	0x73, 0x24, 0x0c, 0xa7, 0xea, 0x9f, 0x69, 0x9a, 0xfe, 0x33, 0x4d, 0xcf, 0xc5, 0x3f, 0xd3, 0xe8,
	0xf8, 0x6e, 0xc1, 0xcd, 0x3b, 0x3d, 0xca, 0x54, 0xa7, 0x8a, 0x1a, 0x28, 0xe1, 0x15, 0x65, 0xce,
	0x3d, 0xe5, 0xa6, 0x99, 0xa7, 0x1f, 0xe0, 0xb0, 0x40, 0x90, 0xda, 0xe4, 0xd6, 0x28, 0x57, 0x89,
	0x3b, 0x77, 0xfb, 0xbb, 0x30, 0x5a, 0xfa, 0x2a, 0xba, 0xfe, 0x0f, 0x3c, 0x9a, 0x77, 0xbd, 0xc8,
	0x88, 0xe1, 0xc1, 0xbb, 0xe6, 0xa6, 0x99, 0xa7, 0x17, 0xba, 0xa1, 0xc4, 0x06, 0x55, 0x5a, 0x34,
	0xbc, 0x53, 0xeb, 0x07, 0x7a, 0xe0, 0x3b, 0xdd, 0x4d, 0xc6, 0x18, 0x30, 0xba, 0xe9, 0xee, 0x70,
	0xa8, 0x68, 0xee, 0xeb, 0xa6, 0x2c, 0xf7, 0xe7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x48, 0x58,
	0x13, 0xcb, 0x48, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdminItemServiceClient is the client API for AdminItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminItemServiceClient interface {
	AdminItem(ctx context.Context, in *AdminItemRequest, opts ...grpc.CallOption) (*AdminItemResponse, error)
	AdminCreateDraftItem(ctx context.Context, in *AdminDraftRequest, opts ...grpc.CallOption) (*AdminItemResponse, error)
	AdminEditItem(ctx context.Context, in *AdminEditItemRequest, opts ...grpc.CallOption) (*AdminItemResponse, error)
	AdminDeleteItem(ctx context.Context, in *AdminDeleteItemRequest, opts ...grpc.CallOption) (*AdminItemsResponse, error)
	AdminDeleteOffer(ctx context.Context, in *AdminDeleteOfferRequest, opts ...grpc.CallOption) (*AdminOffersResponse, error)
	AdminItems(ctx context.Context, in *AdminItemsRequest, opts ...grpc.CallOption) (*AdminItemsResponse, error)
	AdminGetUploadImages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AdminItemImagesResponse, error)
	AdminItemCategories(ctx context.Context, in *AdminItemRequest, opts ...grpc.CallOption) (*AdminCategoriesResponse, error)
	AdminItemBindCategory(ctx context.Context, in *AdminItemBindRequest, opts ...grpc.CallOption) (*AdminCategoriesResponse, error)
	AdminItemUnbindCategory(ctx context.Context, in *AdminItemBindRequest, opts ...grpc.CallOption) (*AdminCategoriesResponse, error)
	AdminItemProperties(ctx context.Context, in *AdminItemRequest, opts ...grpc.CallOption) (*AdminPropertiesResponse, error)
	AdminItemOffers(ctx context.Context, in *AdminOffersRequest, opts ...grpc.CallOption) (*AdminOffersResponse, error)
	AdminUploadOffer(ctx context.Context, in *AdminUploadOfferRequest, opts ...grpc.CallOption) (*AdminItemResponse, error)
}

type adminItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminItemServiceClient(cc grpc.ClientConnInterface) AdminItemServiceClient {
	return &adminItemServiceClient{cc}
}

func (c *adminItemServiceClient) AdminItem(ctx context.Context, in *AdminItemRequest, opts ...grpc.CallOption) (*AdminItemResponse, error) {
	out := new(AdminItemResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminCreateDraftItem(ctx context.Context, in *AdminDraftRequest, opts ...grpc.CallOption) (*AdminItemResponse, error) {
	out := new(AdminItemResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminCreateDraftItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminEditItem(ctx context.Context, in *AdminEditItemRequest, opts ...grpc.CallOption) (*AdminItemResponse, error) {
	out := new(AdminItemResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminEditItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminDeleteItem(ctx context.Context, in *AdminDeleteItemRequest, opts ...grpc.CallOption) (*AdminItemsResponse, error) {
	out := new(AdminItemsResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminDeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminDeleteOffer(ctx context.Context, in *AdminDeleteOfferRequest, opts ...grpc.CallOption) (*AdminOffersResponse, error) {
	out := new(AdminOffersResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminDeleteOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminItems(ctx context.Context, in *AdminItemsRequest, opts ...grpc.CallOption) (*AdminItemsResponse, error) {
	out := new(AdminItemsResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminGetUploadImages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AdminItemImagesResponse, error) {
	out := new(AdminItemImagesResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminGetUploadImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminItemCategories(ctx context.Context, in *AdminItemRequest, opts ...grpc.CallOption) (*AdminCategoriesResponse, error) {
	out := new(AdminCategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminItemCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminItemBindCategory(ctx context.Context, in *AdminItemBindRequest, opts ...grpc.CallOption) (*AdminCategoriesResponse, error) {
	out := new(AdminCategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminItemBindCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminItemUnbindCategory(ctx context.Context, in *AdminItemBindRequest, opts ...grpc.CallOption) (*AdminCategoriesResponse, error) {
	out := new(AdminCategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminItemUnbindCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminItemProperties(ctx context.Context, in *AdminItemRequest, opts ...grpc.CallOption) (*AdminPropertiesResponse, error) {
	out := new(AdminPropertiesResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminItemProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminItemOffers(ctx context.Context, in *AdminOffersRequest, opts ...grpc.CallOption) (*AdminOffersResponse, error) {
	out := new(AdminOffersResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminItemOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminItemServiceClient) AdminUploadOffer(ctx context.Context, in *AdminUploadOfferRequest, opts ...grpc.CallOption) (*AdminItemResponse, error) {
	out := new(AdminItemResponse)
	err := c.cc.Invoke(ctx, "/v1.AdminItemService/AdminUploadOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminItemServiceServer is the server API for AdminItemService service.
type AdminItemServiceServer interface {
	AdminItem(context.Context, *AdminItemRequest) (*AdminItemResponse, error)
	AdminCreateDraftItem(context.Context, *AdminDraftRequest) (*AdminItemResponse, error)
	AdminEditItem(context.Context, *AdminEditItemRequest) (*AdminItemResponse, error)
	AdminDeleteItem(context.Context, *AdminDeleteItemRequest) (*AdminItemsResponse, error)
	AdminDeleteOffer(context.Context, *AdminDeleteOfferRequest) (*AdminOffersResponse, error)
	AdminItems(context.Context, *AdminItemsRequest) (*AdminItemsResponse, error)
	AdminGetUploadImages(context.Context, *empty.Empty) (*AdminItemImagesResponse, error)
	AdminItemCategories(context.Context, *AdminItemRequest) (*AdminCategoriesResponse, error)
	AdminItemBindCategory(context.Context, *AdminItemBindRequest) (*AdminCategoriesResponse, error)
	AdminItemUnbindCategory(context.Context, *AdminItemBindRequest) (*AdminCategoriesResponse, error)
	AdminItemProperties(context.Context, *AdminItemRequest) (*AdminPropertiesResponse, error)
	AdminItemOffers(context.Context, *AdminOffersRequest) (*AdminOffersResponse, error)
	AdminUploadOffer(context.Context, *AdminUploadOfferRequest) (*AdminItemResponse, error)
}

// UnimplementedAdminItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminItemServiceServer struct {
}

func (*UnimplementedAdminItemServiceServer) AdminItem(ctx context.Context, req *AdminItemRequest) (*AdminItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminItem not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminCreateDraftItem(ctx context.Context, req *AdminDraftRequest) (*AdminItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminCreateDraftItem not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminEditItem(ctx context.Context, req *AdminEditItemRequest) (*AdminItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminEditItem not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminDeleteItem(ctx context.Context, req *AdminDeleteItemRequest) (*AdminItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDeleteItem not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminDeleteOffer(ctx context.Context, req *AdminDeleteOfferRequest) (*AdminOffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDeleteOffer not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminItems(ctx context.Context, req *AdminItemsRequest) (*AdminItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminItems not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminGetUploadImages(ctx context.Context, req *empty.Empty) (*AdminItemImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminGetUploadImages not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminItemCategories(ctx context.Context, req *AdminItemRequest) (*AdminCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminItemCategories not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminItemBindCategory(ctx context.Context, req *AdminItemBindRequest) (*AdminCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminItemBindCategory not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminItemUnbindCategory(ctx context.Context, req *AdminItemBindRequest) (*AdminCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminItemUnbindCategory not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminItemProperties(ctx context.Context, req *AdminItemRequest) (*AdminPropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminItemProperties not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminItemOffers(ctx context.Context, req *AdminOffersRequest) (*AdminOffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminItemOffers not implemented")
}
func (*UnimplementedAdminItemServiceServer) AdminUploadOffer(ctx context.Context, req *AdminUploadOfferRequest) (*AdminItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUploadOffer not implemented")
}

func RegisterAdminItemServiceServer(s *grpc.Server, srv AdminItemServiceServer) {
	s.RegisterService(&_AdminItemService_serviceDesc, srv)
}

func _AdminItemService_AdminItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminItem(ctx, req.(*AdminItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminCreateDraftItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminCreateDraftItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminCreateDraftItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminCreateDraftItem(ctx, req.(*AdminDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminEditItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEditItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminEditItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminEditItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminEditItem(ctx, req.(*AdminEditItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminDeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminDeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminDeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminDeleteItem(ctx, req.(*AdminDeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminDeleteOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminDeleteOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminDeleteOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminDeleteOffer(ctx, req.(*AdminDeleteOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminItems(ctx, req.(*AdminItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminGetUploadImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminGetUploadImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminGetUploadImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminGetUploadImages(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminItemCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminItemCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminItemCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminItemCategories(ctx, req.(*AdminItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminItemBindCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminItemBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminItemBindCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminItemBindCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminItemBindCategory(ctx, req.(*AdminItemBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminItemUnbindCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminItemBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminItemUnbindCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminItemUnbindCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminItemUnbindCategory(ctx, req.(*AdminItemBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminItemProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminItemProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminItemProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminItemProperties(ctx, req.(*AdminItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminItemOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminItemOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminItemOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminItemOffers(ctx, req.(*AdminOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminItemService_AdminUploadOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUploadOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminItemServiceServer).AdminUploadOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AdminItemService/AdminUploadOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminItemServiceServer).AdminUploadOffer(ctx, req.(*AdminUploadOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AdminItemService",
	HandlerType: (*AdminItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminItem",
			Handler:    _AdminItemService_AdminItem_Handler,
		},
		{
			MethodName: "AdminCreateDraftItem",
			Handler:    _AdminItemService_AdminCreateDraftItem_Handler,
		},
		{
			MethodName: "AdminEditItem",
			Handler:    _AdminItemService_AdminEditItem_Handler,
		},
		{
			MethodName: "AdminDeleteItem",
			Handler:    _AdminItemService_AdminDeleteItem_Handler,
		},
		{
			MethodName: "AdminDeleteOffer",
			Handler:    _AdminItemService_AdminDeleteOffer_Handler,
		},
		{
			MethodName: "AdminItems",
			Handler:    _AdminItemService_AdminItems_Handler,
		},
		{
			MethodName: "AdminGetUploadImages",
			Handler:    _AdminItemService_AdminGetUploadImages_Handler,
		},
		{
			MethodName: "AdminItemCategories",
			Handler:    _AdminItemService_AdminItemCategories_Handler,
		},
		{
			MethodName: "AdminItemBindCategory",
			Handler:    _AdminItemService_AdminItemBindCategory_Handler,
		},
		{
			MethodName: "AdminItemUnbindCategory",
			Handler:    _AdminItemService_AdminItemUnbindCategory_Handler,
		},
		{
			MethodName: "AdminItemProperties",
			Handler:    _AdminItemService_AdminItemProperties_Handler,
		},
		{
			MethodName: "AdminItemOffers",
			Handler:    _AdminItemService_AdminItemOffers_Handler,
		},
		{
			MethodName: "AdminUploadOffer",
			Handler:    _AdminItemService_AdminUploadOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin-item.proto",
}
