// Code generated by protoc-gen-go. DO NOT EDIT.
// source: category.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State struct {
	Disabled             bool     `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Opened               bool     `protobuf:"varint,2,opt,name=opened,proto3" json:"opened,omitempty"`
	Selected             bool     `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{0}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *State) GetOpened() bool {
	if m != nil {
		return m.Opened
	}
	return false
}

func (m *State) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

type Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               uint32   `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Alias                string   `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Image                string   `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Parent               string   `protobuf:"bytes,7,opt,name=parent,proto3" json:"parent,omitempty"`
	Sort                 uint32   `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	State                *State   `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	SeoTitle             string   `protobuf:"bytes,10,opt,name=seoTitle,proto3" json:"seoTitle,omitempty"`
	SeoDescription       string   `protobuf:"bytes,11,opt,name=seoDescription,proto3" json:"seoDescription,omitempty"`
	SeoKeywords          string   `protobuf:"bytes,12,opt,name=seoKeywords,proto3" json:"seoKeywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{1}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Category) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Category) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Category) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Category) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Category) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *Category) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Category) GetSeoTitle() string {
	if m != nil {
		return m.SeoTitle
	}
	return ""
}

func (m *Category) GetSeoDescription() string {
	if m != nil {
		return m.SeoDescription
	}
	return ""
}

func (m *Category) GetSeoKeywords() string {
	if m != nil {
		return m.SeoKeywords
	}
	return ""
}

type CategoriesResponse struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoriesResponse) Reset()         { *m = CategoriesResponse{} }
func (m *CategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*CategoriesResponse) ProtoMessage()    {}
func (*CategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c6ef5ed29d8d1a1, []int{2}
}

func (m *CategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoriesResponse.Unmarshal(m, b)
}
func (m *CategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoriesResponse.Marshal(b, m, deterministic)
}
func (m *CategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoriesResponse.Merge(m, src)
}
func (m *CategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_CategoriesResponse.Size(m)
}
func (m *CategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoriesResponse proto.InternalMessageInfo

func (m *CategoriesResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func init() {
	proto.RegisterType((*State)(nil), "v1.State")
	proto.RegisterType((*Category)(nil), "v1.Category")
	proto.RegisterType((*CategoriesResponse)(nil), "v1.CategoriesResponse")
}

func init() {
	proto.RegisterFile("category.proto", fileDescriptor_1c6ef5ed29d8d1a1)
}

var fileDescriptor_1c6ef5ed29d8d1a1 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0xb1, 0x13, 0x67, 0xed, 0x71, 0x36, 0x0b, 0x62, 0x09, 0x22, 0x7b, 0x58, 0x93, 0xc3,
	0x92, 0xc3, 0xe2, 0x90, 0xec, 0x75, 0x4f, 0x6d, 0x7a, 0x28, 0x3d, 0x14, 0x9c, 0x42, 0xcf, 0x8e,
	0x3d, 0x35, 0x02, 0xc7, 0x32, 0x92, 0x92, 0x36, 0x4f, 0xd8, 0xd7, 0x2a, 0x1a, 0xd9, 0xa9, 0xe9,
	0x4d, 0xdf, 0x4f, 0x33, 0xdf, 0xfc, 0x61, 0x60, 0x56, 0xe4, 0x06, 0x2b, 0xa9, 0x2e, 0x69, 0xab,
	0xa4, 0x91, 0xcc, 0x3f, 0x6f, 0x16, 0xbf, 0x2a, 0x29, 0xab, 0x1a, 0xd7, 0x44, 0x0e, 0xa7, 0x97,
	0x35, 0x1e, 0x5b, 0xd3, 0x05, 0x2c, 0x9f, 0x21, 0xd8, 0x9b, 0xdc, 0x20, 0x5b, 0x40, 0x58, 0x0a,
	0x9d, 0x1f, 0x6a, 0x2c, 0xb9, 0x97, 0x78, 0xab, 0x30, 0xbb, 0x6a, 0x36, 0x87, 0x89, 0x6c, 0xb1,
	0xc1, 0x92, 0xfb, 0xf4, 0xd3, 0x29, 0x9b, 0xa3, 0xb1, 0xc6, 0xc2, 0x60, 0xc9, 0x47, 0x2e, 0xa7,
	0xd7, 0xcb, 0x77, 0x1f, 0xc2, 0xdb, 0xae, 0x19, 0x36, 0x03, 0x5f, 0x38, 0xdb, 0x28, 0xf3, 0x05,
	0x19, 0x9e, 0x34, 0xaa, 0xfb, 0x1d, 0x19, 0x7e, 0xcf, 0x3a, 0xc5, 0x18, 0x8c, 0x0d, 0xbe, 0x19,
	0x32, 0x8b, 0x32, 0x7a, 0xb3, 0x9f, 0x10, 0xe4, 0xb5, 0xc8, 0x35, 0x1f, 0x13, 0x74, 0x82, 0x25,
	0x10, 0x97, 0xa8, 0x0b, 0x25, 0x5a, 0x23, 0x64, 0xc3, 0x03, 0xfa, 0x1b, 0x22, 0x9b, 0x27, 0x8e,
	0x79, 0x85, 0x7c, 0xe2, 0xf2, 0x48, 0xd8, 0xca, 0x6d, 0xae, 0xb0, 0x31, 0xfc, 0x1b, 0xe1, 0x4e,
	0xd9, 0xca, 0x5a, 0x2a, 0xc3, 0x43, 0xea, 0x87, 0xde, 0xec, 0x37, 0x04, 0xda, 0xee, 0x86, 0x47,
	0x89, 0xb7, 0x8a, 0xb7, 0x51, 0x7a, 0xde, 0xa4, 0xb4, 0xac, 0xcc, 0x71, 0x37, 0xbf, 0x7c, 0x12,
	0xa6, 0x46, 0x0e, 0x64, 0x77, 0xd5, 0xec, 0x0f, 0xcc, 0x34, 0xca, 0xdd, 0xa0, 0xc7, 0x98, 0x22,
	0xbe, 0x50, 0x3b, 0x88, 0x46, 0xf9, 0x80, 0x97, 0x57, 0xa9, 0x4a, 0xcd, 0xa7, 0x6e, 0x90, 0x01,
	0x5a, 0xde, 0x00, 0xeb, 0x16, 0x29, 0x50, 0x67, 0xa8, 0x5b, 0xd9, 0x68, 0x64, 0x7f, 0x01, 0x8a,
	0x2b, 0xe5, 0x5e, 0x32, 0x5a, 0xc5, 0xdb, 0xa9, 0xed, 0xb0, 0x5f, 0x7a, 0x36, 0xf8, 0xdf, 0x3e,
	0xc2, 0x8f, 0x9e, 0xef, 0x51, 0x9d, 0x45, 0x81, 0xec, 0x3f, 0xc0, 0xa7, 0x2d, 0x9b, 0xa7, 0xee,
	0x4a, 0xd2, 0xfe, 0x4a, 0xd2, 0x3b, 0x7b, 0x25, 0x8b, 0xf9, 0xc0, 0x72, 0x50, 0xfe, 0x30, 0xa1,
	0xb8, 0x7f, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x75, 0x51, 0x31, 0x71, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CategoryServiceClient is the client API for CategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CategoryServiceClient interface {
	Categories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CategoriesResponse, error)
}

type categoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryServiceClient(cc grpc.ClientConnInterface) CategoryServiceClient {
	return &categoryServiceClient{cc}
}

func (c *categoryServiceClient) Categories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.CategoryService/Categories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServiceServer is the server API for CategoryService service.
type CategoryServiceServer interface {
	Categories(context.Context, *empty.Empty) (*CategoriesResponse, error)
}

// UnimplementedCategoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCategoryServiceServer struct {
}

func (*UnimplementedCategoryServiceServer) Categories(ctx context.Context, req *empty.Empty) (*CategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Categories not implemented")
}

func RegisterCategoryServiceServer(s *grpc.Server, srv CategoryServiceServer) {
	s.RegisterService(&_CategoryService_serviceDesc, srv)
}

func _CategoryService_Categories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).Categories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CategoryService/Categories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).Categories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CategoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CategoryService",
	HandlerType: (*CategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Categories",
			Handler:    _CategoryService_Categories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "category.proto",
}
