// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currency.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Currency struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShortName            string   `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Rate                 float32  `protobuf:"fixed32,5,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{0}
}

func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (m *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(m, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Currency) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *Currency) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Currency) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type CurrencyRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyRequest) Reset()         { *m = CurrencyRequest{} }
func (m *CurrencyRequest) String() string { return proto.CompactTextString(m) }
func (*CurrencyRequest) ProtoMessage()    {}
func (*CurrencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{1}
}

func (m *CurrencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyRequest.Unmarshal(m, b)
}
func (m *CurrencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyRequest.Marshal(b, m, deterministic)
}
func (m *CurrencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyRequest.Merge(m, src)
}
func (m *CurrencyRequest) XXX_Size() int {
	return xxx_messageInfo_CurrencyRequest.Size(m)
}
func (m *CurrencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyRequest proto.InternalMessageInfo

func (m *CurrencyRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CurrenciesRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrenciesRequest) Reset()         { *m = CurrenciesRequest{} }
func (m *CurrenciesRequest) String() string { return proto.CompactTextString(m) }
func (*CurrenciesRequest) ProtoMessage()    {}
func (*CurrenciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{2}
}

func (m *CurrenciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrenciesRequest.Unmarshal(m, b)
}
func (m *CurrenciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrenciesRequest.Marshal(b, m, deterministic)
}
func (m *CurrenciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrenciesRequest.Merge(m, src)
}
func (m *CurrenciesRequest) XXX_Size() int {
	return xxx_messageInfo_CurrenciesRequest.Size(m)
}
func (m *CurrenciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrenciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrenciesRequest proto.InternalMessageInfo

func (m *CurrenciesRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *CurrenciesRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *CurrenciesRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *CurrenciesRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type CurrencyResponse struct {
	Currency             *Currency `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CurrencyResponse) Reset()         { *m = CurrencyResponse{} }
func (m *CurrencyResponse) String() string { return proto.CompactTextString(m) }
func (*CurrencyResponse) ProtoMessage()    {}
func (*CurrencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{3}
}

func (m *CurrencyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyResponse.Unmarshal(m, b)
}
func (m *CurrencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyResponse.Marshal(b, m, deterministic)
}
func (m *CurrencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyResponse.Merge(m, src)
}
func (m *CurrencyResponse) XXX_Size() int {
	return xxx_messageInfo_CurrencyResponse.Size(m)
}
func (m *CurrencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyResponse proto.InternalMessageInfo

func (m *CurrencyResponse) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

type CurrenciesResponse struct {
	Currencies           []*Currency `protobuf:"bytes,1,rep,name=Currencies,proto3" json:"Currencies,omitempty"`
	Total                uint32      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CurrenciesResponse) Reset()         { *m = CurrenciesResponse{} }
func (m *CurrenciesResponse) String() string { return proto.CompactTextString(m) }
func (*CurrenciesResponse) ProtoMessage()    {}
func (*CurrenciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{4}
}

func (m *CurrenciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrenciesResponse.Unmarshal(m, b)
}
func (m *CurrenciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrenciesResponse.Marshal(b, m, deterministic)
}
func (m *CurrenciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrenciesResponse.Merge(m, src)
}
func (m *CurrenciesResponse) XXX_Size() int {
	return xxx_messageInfo_CurrenciesResponse.Size(m)
}
func (m *CurrenciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrenciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrenciesResponse proto.InternalMessageInfo

func (m *CurrenciesResponse) GetCurrencies() []*Currency {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *CurrenciesResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Currency)(nil), "v1.Currency")
	proto.RegisterType((*CurrencyRequest)(nil), "v1.CurrencyRequest")
	proto.RegisterType((*CurrenciesRequest)(nil), "v1.CurrenciesRequest")
	proto.RegisterType((*CurrencyResponse)(nil), "v1.CurrencyResponse")
	proto.RegisterType((*CurrenciesResponse)(nil), "v1.CurrenciesResponse")
}

func init() {
	proto.RegisterFile("currency.proto", fileDescriptor_d3dc60ed002193ea)
}

var fileDescriptor_d3dc60ed002193ea = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x41, 0x4f, 0xb3, 0x40,
	0x14, 0xcc, 0x52, 0xfa, 0xa5, 0xbc, 0xcf, 0x56, 0x7d, 0x56, 0x43, 0xaa, 0x26, 0xc8, 0x89, 0x83,
	0x21, 0x69, 0x8d, 0x27, 0xbd, 0x79, 0xf7, 0x40, 0x2f, 0xde, 0x1a, 0x84, 0x17, 0xdd, 0x44, 0x59,
	0xdc, 0x5d, 0x48, 0xec, 0xdd, 0xff, 0x6d, 0x58, 0x96, 0x42, 0xeb, 0x89, 0x61, 0x66, 0xde, 0xbe,
	0x61, 0x58, 0x98, 0x65, 0x95, 0x94, 0x54, 0x64, 0xdf, 0x71, 0x29, 0x85, 0x16, 0xe8, 0xd4, 0xcb,
	0xb0, 0x82, 0xc9, 0x93, 0x65, 0x71, 0x06, 0x0e, 0xcf, 0x7d, 0x16, 0xb0, 0x68, 0x9a, 0x38, 0x3c,
	0x47, 0x04, 0xb7, 0x48, 0x3f, 0xc9, 0x77, 0x02, 0x16, 0x79, 0x89, 0xc1, 0x78, 0x0d, 0xa0, 0xde,
	0x85, 0xd4, 0x1b, 0xa3, 0x8c, 0x8c, 0xe2, 0x19, 0xe6, 0xb9, 0x91, 0x11, 0xdc, 0x4c, 0xe4, 0xe4,
	0xbb, 0xed, 0x48, 0x83, 0x1b, 0x4e, 0xa6, 0x9a, 0xfc, 0x71, 0xc0, 0x22, 0x27, 0x31, 0x38, 0xbc,
	0x81, 0xe3, 0x6e, 0x6d, 0x42, 0x5f, 0x15, 0x29, 0x7d, 0xb8, 0x3d, 0xac, 0xe1, 0xd4, 0x5a, 0x38,
	0xa9, 0xce, 0x84, 0xe0, 0x96, 0xe9, 0x1b, 0x59, 0x9b, 0xc1, 0x78, 0x09, 0x5e, 0xf3, 0xdc, 0x28,
	0xbe, 0x6d, 0xb3, 0x4e, 0x93, 0x49, 0x43, 0xac, 0xf9, 0xd6, 0x2c, 0x57, 0x42, 0x6a, 0x9b, 0xd4,
	0x60, 0xbc, 0x02, 0x2f, 0xe7, 0x92, 0x32, 0xcd, 0x45, 0x61, 0x93, 0xf6, 0x44, 0xf8, 0x08, 0x27,
	0x7d, 0x34, 0x55, 0x8a, 0x42, 0x11, 0x46, 0x30, 0xe9, 0xba, 0x33, 0xab, 0xff, 0xaf, 0x8e, 0xe2,
	0x7a, 0x19, 0xef, 0x7c, 0x3b, 0x35, 0x7c, 0x01, 0x1c, 0xa6, 0xb6, 0xf3, 0xb7, 0x00, 0x3d, 0xeb,
	0xb3, 0x60, 0xf4, 0xe7, 0x84, 0x81, 0x8e, 0x73, 0x18, 0x6b, 0xa1, 0xd3, 0x0f, 0xfb, 0x31, 0xed,
	0xcb, 0xea, 0x87, 0xf5, 0x9d, 0xad, 0x49, 0xd6, 0x3c, 0x23, 0xbc, 0x1f, 0xfc, 0xbd, 0xb3, 0xbd,
	0xf3, 0xda, 0xbe, 0x16, 0xf3, 0x7d, 0xd2, 0xc6, 0x79, 0x18, 0xc6, 0xc1, 0xf3, 0x81, 0xa7, 0xaf,
	0x7a, 0x71, 0x71, 0x48, 0xb7, 0xc3, 0xaf, 0xff, 0xcc, 0xe5, 0xb9, 0xfb, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0x5c, 0xbe, 0xa6, 0x4e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CurrencyServiceClient is the client API for CurrencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CurrencyServiceClient interface {
	Currency(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyResponse, error)
	Currencies(ctx context.Context, in *CurrenciesRequest, opts ...grpc.CallOption) (*CurrenciesResponse, error)
}

type currencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyServiceClient(cc grpc.ClientConnInterface) CurrencyServiceClient {
	return &currencyServiceClient{cc}
}

func (c *currencyServiceClient) Currency(ctx context.Context, in *CurrencyRequest, opts ...grpc.CallOption) (*CurrencyResponse, error) {
	out := new(CurrencyResponse)
	err := c.cc.Invoke(ctx, "/v1.CurrencyService/Currency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) Currencies(ctx context.Context, in *CurrenciesRequest, opts ...grpc.CallOption) (*CurrenciesResponse, error) {
	out := new(CurrenciesResponse)
	err := c.cc.Invoke(ctx, "/v1.CurrencyService/Currencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyServiceServer is the server API for CurrencyService service.
type CurrencyServiceServer interface {
	Currency(context.Context, *CurrencyRequest) (*CurrencyResponse, error)
	Currencies(context.Context, *CurrenciesRequest) (*CurrenciesResponse, error)
}

// UnimplementedCurrencyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCurrencyServiceServer struct {
}

func (*UnimplementedCurrencyServiceServer) Currency(ctx context.Context, req *CurrencyRequest) (*CurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Currency not implemented")
}
func (*UnimplementedCurrencyServiceServer) Currencies(ctx context.Context, req *CurrenciesRequest) (*CurrenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Currencies not implemented")
}

func RegisterCurrencyServiceServer(s *grpc.Server, srv CurrencyServiceServer) {
	s.RegisterService(&_CurrencyService_serviceDesc, srv)
}

func _CurrencyService_Currency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).Currency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CurrencyService/Currency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).Currency(ctx, req.(*CurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_Currencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).Currencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CurrencyService/Currencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).Currencies(ctx, req.(*CurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CurrencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CurrencyService",
	HandlerType: (*CurrencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Currency",
			Handler:    _CurrencyService_Currency_Handler,
		},
		{
			MethodName: "Currencies",
			Handler:    _CurrencyService_Currencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "currency.proto",
}
