// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32       `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VendorId             uint32       `protobuf:"varint,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ParentId             uint32       `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CategoryId           uint32       `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Title                string       `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Article              string       `protobuf:"bytes,7,opt,name=article,proto3" json:"article,omitempty"`
	Alias                string       `protobuf:"bytes,8,opt,name=alias,proto3" json:"alias,omitempty"`
	Description          string       `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32      `protobuf:"fixed32,10,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice             float32      `protobuf:"fixed32,11,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	CurrencyId           uint32       `protobuf:"varint,12,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Count                int32        `protobuf:"varint,13,opt,name=count,proto3" json:"count,omitempty"`
	Disable              bool         `protobuf:"varint,14,opt,name=disable,proto3" json:"disable,omitempty"`
	Sort                 uint32       `protobuf:"varint,15,opt,name=sort,proto3" json:"sort,omitempty"`
	SeoTitle             string       `protobuf:"bytes,16,opt,name=seo_title,json=seoTitle,proto3" json:"seo_title,omitempty"`
	SeoDescription       string       `protobuf:"bytes,17,opt,name=seo_description,json=seoDescription,proto3" json:"seo_description,omitempty"`
	SeoKeywords          string       `protobuf:"bytes,18,opt,name=seo_keywords,json=seoKeywords,proto3" json:"seo_keywords,omitempty"`
	Images               []*ItemImage `protobuf:"bytes,19,rep,name=images,proto3" json:"images,omitempty"`
	Offers               []*Item      `protobuf:"bytes,20,rep,name=offers,proto3" json:"offers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Item) GetVendorId() uint32 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *Item) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Item) GetCategoryId() uint32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *Item) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetOldPrice() float32 {
	if m != nil {
		return m.OldPrice
	}
	return 0
}

func (m *Item) GetCurrencyId() uint32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *Item) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Item) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

func (m *Item) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *Item) GetSeoTitle() string {
	if m != nil {
		return m.SeoTitle
	}
	return ""
}

func (m *Item) GetSeoDescription() string {
	if m != nil {
		return m.SeoDescription
	}
	return ""
}

func (m *Item) GetSeoKeywords() string {
	if m != nil {
		return m.SeoKeywords
	}
	return ""
}

func (m *Item) GetImages() []*ItemImage {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Item) GetOffers() []*Item {
	if m != nil {
		return m.Offers
	}
	return nil
}

type ItemImage struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               uint32   `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Filename             string   `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Sort                 uint32   `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	PropertyValueId      uint32   `protobuf:"varint,6,opt,name=property_value_id,json=propertyValueId,proto3" json:"property_value_id,omitempty"`
	Main                 bool     `protobuf:"varint,7,opt,name=main,proto3" json:"main,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemImage) Reset()         { *m = ItemImage{} }
func (m *ItemImage) String() string { return proto.CompactTextString(m) }
func (*ItemImage) ProtoMessage()    {}
func (*ItemImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *ItemImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemImage.Unmarshal(m, b)
}
func (m *ItemImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemImage.Marshal(b, m, deterministic)
}
func (m *ItemImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemImage.Merge(m, src)
}
func (m *ItemImage) XXX_Size() int {
	return xxx_messageInfo_ItemImage.Size(m)
}
func (m *ItemImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemImage.DiscardUnknown(m)
}

var xxx_messageInfo_ItemImage proto.InternalMessageInfo

func (m *ItemImage) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ItemImage) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ItemImage) GetItemId() uint32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ItemImage) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ItemImage) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *ItemImage) GetPropertyValueId() uint32 {
	if m != nil {
		return m.PropertyValueId
	}
	return 0
}

func (m *ItemImage) GetMain() bool {
	if m != nil {
		return m.Main
	}
	return false
}

type ItemProperty struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	PropertyValueIds     []uint32 `protobuf:"varint,2,rep,packed,name=property_value_ids,json=propertyValueIds,proto3" json:"property_value_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemProperty) Reset()         { *m = ItemProperty{} }
func (m *ItemProperty) String() string { return proto.CompactTextString(m) }
func (*ItemProperty) ProtoMessage()    {}
func (*ItemProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *ItemProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemProperty.Unmarshal(m, b)
}
func (m *ItemProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemProperty.Marshal(b, m, deterministic)
}
func (m *ItemProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemProperty.Merge(m, src)
}
func (m *ItemProperty) XXX_Size() int {
	return xxx_messageInfo_ItemProperty.Size(m)
}
func (m *ItemProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemProperty.DiscardUnknown(m)
}

var xxx_messageInfo_ItemProperty proto.InternalMessageInfo

func (m *ItemProperty) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ItemProperty) GetPropertyValueIds() []uint32 {
	if m != nil {
		return m.PropertyValueIds
	}
	return nil
}

type ItemRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRequest) Reset()         { *m = ItemRequest{} }
func (m *ItemRequest) String() string { return proto.CompactTextString(m) }
func (*ItemRequest) ProtoMessage()    {}
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *ItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRequest.Unmarshal(m, b)
}
func (m *ItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRequest.Marshal(b, m, deterministic)
}
func (m *ItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRequest.Merge(m, src)
}
func (m *ItemRequest) XXX_Size() int {
	return xxx_messageInfo_ItemRequest.Size(m)
}
func (m *ItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRequest proto.InternalMessageInfo

func (m *ItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DraftRequest struct {
	ParentId             uint32   `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DraftRequest) Reset()         { *m = DraftRequest{} }
func (m *DraftRequest) String() string { return proto.CompactTextString(m) }
func (*DraftRequest) ProtoMessage()    {}
func (*DraftRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{4}
}

func (m *DraftRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DraftRequest.Unmarshal(m, b)
}
func (m *DraftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DraftRequest.Marshal(b, m, deterministic)
}
func (m *DraftRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DraftRequest.Merge(m, src)
}
func (m *DraftRequest) XXX_Size() int {
	return xxx_messageInfo_DraftRequest.Size(m)
}
func (m *DraftRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DraftRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DraftRequest proto.InternalMessageInfo

func (m *DraftRequest) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type ItemsRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsRequest) Reset()         { *m = ItemsRequest{} }
func (m *ItemsRequest) String() string { return proto.CompactTextString(m) }
func (*ItemsRequest) ProtoMessage()    {}
func (*ItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{5}
}

func (m *ItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsRequest.Unmarshal(m, b)
}
func (m *ItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsRequest.Marshal(b, m, deterministic)
}
func (m *ItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsRequest.Merge(m, src)
}
func (m *ItemsRequest) XXX_Size() int {
	return xxx_messageInfo_ItemsRequest.Size(m)
}
func (m *ItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsRequest proto.InternalMessageInfo

func (m *ItemsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ItemsRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ItemsRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ItemsRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type OffersRequest struct {
	ItemId               uint32   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffersRequest) Reset()         { *m = OffersRequest{} }
func (m *OffersRequest) String() string { return proto.CompactTextString(m) }
func (*OffersRequest) ProtoMessage()    {}
func (*OffersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{6}
}

func (m *OffersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffersRequest.Unmarshal(m, b)
}
func (m *OffersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffersRequest.Marshal(b, m, deterministic)
}
func (m *OffersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffersRequest.Merge(m, src)
}
func (m *OffersRequest) XXX_Size() int {
	return xxx_messageInfo_OffersRequest.Size(m)
}
func (m *OffersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OffersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OffersRequest proto.InternalMessageInfo

func (m *OffersRequest) GetItemId() uint32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *OffersRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *OffersRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *OffersRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *OffersRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type EditItemRequest struct {
	Id                   uint32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             uint32          `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Title                string          `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Article              string          `protobuf:"bytes,4,opt,name=article,proto3" json:"article,omitempty"`
	Alias                string          `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	Count                int32           `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Description          string          `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32         `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice             float32         `protobuf:"fixed32,9,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	CurrencyId           uint32          `protobuf:"varint,10,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Disable              bool            `protobuf:"varint,11,opt,name=disable,proto3" json:"disable,omitempty"`
	Sort                 uint32          `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,omitempty"`
	ItemImages           []uint32        `protobuf:"varint,13,rep,packed,name=item_images,json=itemImages,proto3" json:"item_images,omitempty"`
	UploadImages         []uint32        `protobuf:"varint,14,rep,packed,name=upload_images,json=uploadImages,proto3" json:"upload_images,omitempty"`
	Properties           []*ItemProperty `protobuf:"bytes,15,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EditItemRequest) Reset()         { *m = EditItemRequest{} }
func (m *EditItemRequest) String() string { return proto.CompactTextString(m) }
func (*EditItemRequest) ProtoMessage()    {}
func (*EditItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{7}
}

func (m *EditItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditItemRequest.Unmarshal(m, b)
}
func (m *EditItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditItemRequest.Marshal(b, m, deterministic)
}
func (m *EditItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditItemRequest.Merge(m, src)
}
func (m *EditItemRequest) XXX_Size() int {
	return xxx_messageInfo_EditItemRequest.Size(m)
}
func (m *EditItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditItemRequest proto.InternalMessageInfo

func (m *EditItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditItemRequest) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *EditItemRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditItemRequest) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *EditItemRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *EditItemRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *EditItemRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditItemRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *EditItemRequest) GetOldPrice() float32 {
	if m != nil {
		return m.OldPrice
	}
	return 0
}

func (m *EditItemRequest) GetCurrencyId() uint32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *EditItemRequest) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

func (m *EditItemRequest) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *EditItemRequest) GetItemImages() []uint32 {
	if m != nil {
		return m.ItemImages
	}
	return nil
}

func (m *EditItemRequest) GetUploadImages() []uint32 {
	if m != nil {
		return m.UploadImages
	}
	return nil
}

func (m *EditItemRequest) GetProperties() []*ItemProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

type DeleteItemRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemRequest) Reset()         { *m = DeleteItemRequest{} }
func (m *DeleteItemRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteItemRequest) ProtoMessage()    {}
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{8}
}

func (m *DeleteItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemRequest.Unmarshal(m, b)
}
func (m *DeleteItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemRequest.Marshal(b, m, deterministic)
}
func (m *DeleteItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemRequest.Merge(m, src)
}
func (m *DeleteItemRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteItemRequest.Size(m)
}
func (m *DeleteItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemRequest proto.InternalMessageInfo

func (m *DeleteItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteItemRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *DeleteItemRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *DeleteItemRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *DeleteItemRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type DeleteOfferRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             uint32   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOfferRequest) Reset()         { *m = DeleteOfferRequest{} }
func (m *DeleteOfferRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOfferRequest) ProtoMessage()    {}
func (*DeleteOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{9}
}

func (m *DeleteOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOfferRequest.Unmarshal(m, b)
}
func (m *DeleteOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOfferRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOfferRequest.Merge(m, src)
}
func (m *DeleteOfferRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOfferRequest.Size(m)
}
func (m *DeleteOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOfferRequest proto.InternalMessageInfo

func (m *DeleteOfferRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteOfferRequest) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *DeleteOfferRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *DeleteOfferRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *DeleteOfferRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *DeleteOfferRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type ItemBindRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId           string   `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemBindRequest) Reset()         { *m = ItemBindRequest{} }
func (m *ItemBindRequest) String() string { return proto.CompactTextString(m) }
func (*ItemBindRequest) ProtoMessage()    {}
func (*ItemBindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{10}
}

func (m *ItemBindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemBindRequest.Unmarshal(m, b)
}
func (m *ItemBindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemBindRequest.Marshal(b, m, deterministic)
}
func (m *ItemBindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemBindRequest.Merge(m, src)
}
func (m *ItemBindRequest) XXX_Size() int {
	return xxx_messageInfo_ItemBindRequest.Size(m)
}
func (m *ItemBindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemBindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemBindRequest proto.InternalMessageInfo

func (m *ItemBindRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ItemBindRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

type UploadOfferRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ParentId             uint32   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CategoryId           uint32   `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency             string   `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Images               []string `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	Properties           []uint32 `protobuf:"varint,8,rep,packed,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadOfferRequest) Reset()         { *m = UploadOfferRequest{} }
func (m *UploadOfferRequest) String() string { return proto.CompactTextString(m) }
func (*UploadOfferRequest) ProtoMessage()    {}
func (*UploadOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{11}
}

func (m *UploadOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadOfferRequest.Unmarshal(m, b)
}
func (m *UploadOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadOfferRequest.Marshal(b, m, deterministic)
}
func (m *UploadOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadOfferRequest.Merge(m, src)
}
func (m *UploadOfferRequest) XXX_Size() int {
	return xxx_messageInfo_UploadOfferRequest.Size(m)
}
func (m *UploadOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadOfferRequest proto.InternalMessageInfo

func (m *UploadOfferRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UploadOfferRequest) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *UploadOfferRequest) GetCategoryId() uint32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *UploadOfferRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UploadOfferRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *UploadOfferRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UploadOfferRequest) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *UploadOfferRequest) GetProperties() []uint32 {
	if m != nil {
		return m.Properties
	}
	return nil
}

type ItemResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemResponse) Reset()         { *m = ItemResponse{} }
func (m *ItemResponse) String() string { return proto.CompactTextString(m) }
func (*ItemResponse) ProtoMessage()    {}
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{12}
}

func (m *ItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemResponse.Unmarshal(m, b)
}
func (m *ItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemResponse.Marshal(b, m, deterministic)
}
func (m *ItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemResponse.Merge(m, src)
}
func (m *ItemResponse) XXX_Size() int {
	return xxx_messageInfo_ItemResponse.Size(m)
}
func (m *ItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemResponse proto.InternalMessageInfo

func (m *ItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type ItemsResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsResponse) Reset()         { *m = ItemsResponse{} }
func (m *ItemsResponse) String() string { return proto.CompactTextString(m) }
func (*ItemsResponse) ProtoMessage()    {}
func (*ItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{13}
}

func (m *ItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsResponse.Unmarshal(m, b)
}
func (m *ItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsResponse.Marshal(b, m, deterministic)
}
func (m *ItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsResponse.Merge(m, src)
}
func (m *ItemsResponse) XXX_Size() int {
	return xxx_messageInfo_ItemsResponse.Size(m)
}
func (m *ItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsResponse proto.InternalMessageInfo

func (m *ItemsResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ItemsResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type OffersResponse struct {
	Offers               []*Item  `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffersResponse) Reset()         { *m = OffersResponse{} }
func (m *OffersResponse) String() string { return proto.CompactTextString(m) }
func (*OffersResponse) ProtoMessage()    {}
func (*OffersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{14}
}

func (m *OffersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffersResponse.Unmarshal(m, b)
}
func (m *OffersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffersResponse.Marshal(b, m, deterministic)
}
func (m *OffersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffersResponse.Merge(m, src)
}
func (m *OffersResponse) XXX_Size() int {
	return xxx_messageInfo_OffersResponse.Size(m)
}
func (m *OffersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OffersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OffersResponse proto.InternalMessageInfo

func (m *OffersResponse) GetOffers() []*Item {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *OffersResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ItemImagesResponse struct {
	Images               []*ItemImage `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ItemImagesResponse) Reset()         { *m = ItemImagesResponse{} }
func (m *ItemImagesResponse) String() string { return proto.CompactTextString(m) }
func (*ItemImagesResponse) ProtoMessage()    {}
func (*ItemImagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{15}
}

func (m *ItemImagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemImagesResponse.Unmarshal(m, b)
}
func (m *ItemImagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemImagesResponse.Marshal(b, m, deterministic)
}
func (m *ItemImagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemImagesResponse.Merge(m, src)
}
func (m *ItemImagesResponse) XXX_Size() int {
	return xxx_messageInfo_ItemImagesResponse.Size(m)
}
func (m *ItemImagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemImagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemImagesResponse proto.InternalMessageInfo

func (m *ItemImagesResponse) GetImages() []*ItemImage {
	if m != nil {
		return m.Images
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "v1.Item")
	proto.RegisterType((*ItemImage)(nil), "v1.ItemImage")
	proto.RegisterType((*ItemProperty)(nil), "v1.ItemProperty")
	proto.RegisterType((*ItemRequest)(nil), "v1.ItemRequest")
	proto.RegisterType((*DraftRequest)(nil), "v1.DraftRequest")
	proto.RegisterType((*ItemsRequest)(nil), "v1.ItemsRequest")
	proto.RegisterType((*OffersRequest)(nil), "v1.OffersRequest")
	proto.RegisterType((*EditItemRequest)(nil), "v1.EditItemRequest")
	proto.RegisterType((*DeleteItemRequest)(nil), "v1.DeleteItemRequest")
	proto.RegisterType((*DeleteOfferRequest)(nil), "v1.DeleteOfferRequest")
	proto.RegisterType((*ItemBindRequest)(nil), "v1.ItemBindRequest")
	proto.RegisterType((*UploadOfferRequest)(nil), "v1.UploadOfferRequest")
	proto.RegisterType((*ItemResponse)(nil), "v1.ItemResponse")
	proto.RegisterType((*ItemsResponse)(nil), "v1.ItemsResponse")
	proto.RegisterType((*OffersResponse)(nil), "v1.OffersResponse")
	proto.RegisterType((*ItemImagesResponse)(nil), "v1.ItemImagesResponse")
}

func init() {
	proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df)
}

var fileDescriptor_6007f868cf6553df = []byte{
	// 1135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x92, 0xdb, 0x44,
	0x10, 0x2e, 0xf9, 0x57, 0x6e, 0xff, 0xee, 0x24, 0x6c, 0x54, 0x4e, 0x48, 0x8c, 0x28, 0x0a, 0x03,
	0x29, 0x87, 0x24, 0x05, 0x14, 0xc5, 0x81, 0x4a, 0xb2, 0x5b, 0xe0, 0xe2, 0xc0, 0x96, 0xc2, 0x72,
	0xdd, 0xd2, 0x5a, 0xbd, 0xae, 0x29, 0x64, 0x8f, 0xa3, 0x91, 0x97, 0xda, 0x3c, 0x00, 0x17, 0x5e,
	0x83, 0x67, 0xe0, 0x04, 0xaf, 0xc4, 0x89, 0x07, 0xa0, 0xa6, 0x47, 0x23, 0x8d, 0xe5, 0x95, 0x0f,
	0x39, 0x70, 0xd3, 0x74, 0xf7, 0xcc, 0x7c, 0xd3, 0xfd, 0xf5, 0xd7, 0x02, 0xe0, 0x29, 0xae, 0x66,
	0x9b, 0x44, 0xa4, 0x82, 0xd5, 0xae, 0x9f, 0x8e, 0xef, 0x2f, 0x85, 0x58, 0xc6, 0xf8, 0x84, 0x2c,
	0x97, 0xdb, 0xab, 0x27, 0xb8, 0xda, 0xa4, 0x37, 0x3a, 0x60, 0x3c, 0x58, 0x84, 0x29, 0x2e, 0x45,
	0x92, 0xaf, 0x37, 0x89, 0xd8, 0x60, 0x62, 0xfc, 0xfe, 0x5f, 0x0d, 0x68, 0xcc, 0x53, 0x5c, 0xb1,
	0x01, 0xd4, 0x78, 0xe4, 0x39, 0x13, 0x67, 0xda, 0x09, 0x6a, 0x3c, 0x62, 0xf7, 0xa0, 0xbd, 0x95,
	0x98, 0x5c, 0xf0, 0xc8, 0xab, 0x4d, 0x9c, 0x69, 0x3f, 0x68, 0xa9, 0xe5, 0x3c, 0x62, 0xf7, 0xa1,
	0x73, 0x8d, 0xeb, 0x48, 0x90, 0xab, 0x4e, 0x2e, 0x57, 0x1b, 0xb4, 0x73, 0x13, 0x26, 0xb8, 0x4e,
	0x95, 0xb3, 0xa1, 0x9d, 0xda, 0x30, 0x8f, 0xd8, 0x23, 0xe8, 0x1a, 0x34, 0xca, 0xdd, 0x24, 0x37,
	0x18, 0xd3, 0x3c, 0x62, 0x77, 0xa1, 0x99, 0xf2, 0x34, 0x46, 0xaf, 0x45, 0x30, 0xf4, 0x82, 0x79,
	0xd0, 0x0e, 0x93, 0x94, 0x2f, 0x62, 0xf4, 0xda, 0x64, 0x37, 0x4b, 0x15, 0x1f, 0xc6, 0x3c, 0x94,
	0x9e, 0xab, 0xe3, 0x69, 0xc1, 0x26, 0xd0, 0x8d, 0x50, 0x2e, 0x12, 0xbe, 0x49, 0xb9, 0x58, 0x7b,
	0x1d, 0xf2, 0xd9, 0x26, 0xb5, 0x6f, 0x93, 0xf0, 0x05, 0x7a, 0x30, 0x71, 0xa6, 0xb5, 0x40, 0x2f,
	0x14, 0x76, 0x11, 0x47, 0x17, 0xda, 0xd3, 0x25, 0x8f, 0x2b, 0xe2, 0xe8, 0x8c, 0x9c, 0x0a, 0xfb,
	0x36, 0x49, 0x70, 0xbd, 0x20, 0xec, 0xbd, 0x0c, 0x7b, 0x66, 0xd2, 0xd8, 0x17, 0x62, 0xbb, 0x4e,
	0xbd, 0xfe, 0xc4, 0x99, 0x36, 0x03, 0xbd, 0x50, 0xd8, 0x23, 0x2e, 0xc3, 0xcb, 0x18, 0xbd, 0xc1,
	0xc4, 0x99, 0xba, 0x81, 0x59, 0x32, 0x06, 0x0d, 0x29, 0x92, 0xd4, 0x1b, 0xd2, 0x49, 0xf4, 0xad,
	0x10, 0x48, 0x14, 0x17, 0x3a, 0x07, 0x23, 0xc2, 0xed, 0x4a, 0x14, 0x3f, 0x51, 0x1a, 0x3e, 0x86,
	0xa1, 0x72, 0xda, 0x4f, 0x3b, 0xa2, 0x90, 0x81, 0x44, 0x71, 0x62, 0xbd, 0xee, 0x03, 0xe8, 0xa9,
	0xc0, 0x5f, 0xf0, 0xe6, 0x57, 0x91, 0x44, 0xd2, 0x63, 0x3a, 0x01, 0x12, 0xc5, 0x0f, 0x99, 0x89,
	0x7d, 0x04, 0x2d, 0xbe, 0x0a, 0x97, 0x28, 0xbd, 0x3b, 0x93, 0xfa, 0xb4, 0xfb, 0xac, 0x3f, 0xbb,
	0x7e, 0x3a, 0x53, 0x34, 0x98, 0x2b, 0x6b, 0x90, 0x39, 0xd9, 0x04, 0x5a, 0xe2, 0xea, 0x0a, 0x13,
	0xe9, 0xdd, 0xa5, 0x30, 0xd7, 0x84, 0x05, 0x99, 0xdd, 0xff, 0xdb, 0x81, 0x4e, 0xbe, 0xcf, 0xe2,
	0x50, 0xff, 0x30, 0x87, 0xee, 0x41, 0x5b, 0x91, 0xb8, 0x60, 0x50, 0x4b, 0x2d, 0xe7, 0x11, 0x1b,
	0x83, 0x7b, 0xc5, 0x63, 0x5c, 0x87, 0x2b, 0x24, 0xfa, 0x74, 0x82, 0x7c, 0x9d, 0x67, 0xac, 0x69,
	0x65, 0xec, 0x53, 0x38, 0x32, 0x84, 0xbe, 0xb8, 0x0e, 0xe3, 0x2d, 0xaa, 0x23, 0x5b, 0x14, 0x30,
	0x34, 0x8e, 0x9f, 0x95, 0x7d, 0x1e, 0xa9, 0xfd, 0xab, 0x90, 0xaf, 0x89, 0x44, 0x6e, 0x40, 0xdf,
	0xfe, 0x19, 0xf4, 0x14, 0xfc, 0xb3, 0x2c, 0x54, 0xc5, 0x2c, 0x44, 0x84, 0x59, 0x1f, 0xd0, 0x37,
	0x7b, 0x0c, 0x6c, 0xef, 0x0e, 0xe9, 0xd5, 0x26, 0xf5, 0x69, 0x3f, 0x18, 0x95, 0x2e, 0x91, 0xfe,
	0xfb, 0xd0, 0xa5, 0x0c, 0xe1, 0x9b, 0x2d, 0xca, 0xb4, 0x9c, 0x12, 0xff, 0x33, 0xe8, 0x9d, 0x24,
	0xe1, 0x55, 0x6a, 0xfc, 0x3b, 0x0d, 0xe3, 0xec, 0x36, 0x8c, 0xff, 0x46, 0xa3, 0x93, 0x26, 0x98,
	0x41, 0x63, 0x13, 0x2e, 0x31, 0x8b, 0xa3, 0x6f, 0x7d, 0xc0, 0x12, 0x2f, 0x24, 0x7f, 0x8b, 0x59,
	0x96, 0x5d, 0x65, 0x78, 0xcd, 0xdf, 0x16, 0x29, 0xab, 0xeb, 0xe7, 0x50, 0xca, 0x1e, 0x40, 0x27,
	0xe2, 0x09, 0x2e, 0x88, 0x41, 0x3a, 0xc7, 0x85, 0xc1, 0xff, 0xdd, 0x81, 0xfe, 0x8f, 0x54, 0x5b,
	0x73, 0xa9, 0x55, 0x2b, 0x67, 0xa7, 0x56, 0x06, 0x4d, 0xad, 0x0a, 0x4d, 0xbd, 0x02, 0x4d, 0xa3,
	0x0a, 0x4d, 0xb3, 0x8c, 0xe6, 0xcf, 0x3a, 0x0c, 0x4f, 0x23, 0x9e, 0x1e, 0xc8, 0xe8, 0x6e, 0x06,
	0x6b, 0x25, 0xc9, 0xc9, 0x15, 0xa5, 0x5e, 0xa1, 0x28, 0x8d, 0x0a, 0x45, 0x69, 0xda, 0x8a, 0x92,
	0xf7, 0x76, 0xcb, 0xee, 0xed, 0x92, 0xce, 0xb4, 0x0f, 0xe8, 0x8c, 0x5b, 0xa9, 0x33, 0x9d, 0xc3,
	0x3a, 0x03, 0x7b, 0x3a, 0x63, 0x29, 0x4a, 0xf7, 0x76, 0x45, 0xe9, 0x59, 0xfd, 0xf1, 0x08, 0xba,
	0xba, 0x78, 0xba, 0xdb, 0xfb, 0x44, 0x5a, 0x1a, 0x20, 0x73, 0xdd, 0xe2, 0x1f, 0x42, 0x7f, 0xbb,
	0x89, 0x45, 0x18, 0x99, 0x90, 0x01, 0x85, 0xf4, 0xb4, 0x31, 0x0b, 0xfa, 0x1c, 0x20, 0xe3, 0x39,
	0x47, 0xe9, 0x0d, 0x49, 0x0b, 0x46, 0x46, 0x0b, 0x4c, 0xef, 0x04, 0x56, 0x8c, 0xff, 0x9b, 0x03,
	0x47, 0x27, 0x18, 0x63, 0x8a, 0x87, 0x4a, 0xf7, 0x3f, 0x30, 0xe8, 0x0f, 0x07, 0x98, 0x06, 0x42,
	0xac, 0x7e, 0x27, 0x12, 0x19, 0x98, 0xf5, 0x2a, 0x98, 0x8d, 0x0a, 0x98, 0xcd, 0x2a, 0x98, 0xad,
	0x32, 0xcc, 0x97, 0x30, 0x54, 0x89, 0x7a, 0xc9, 0xd7, 0x51, 0x15, 0xc4, 0xd2, 0xf4, 0xac, 0xd1,
	0x11, 0xd6, 0xf4, 0xf4, 0xff, 0x75, 0x80, 0x9d, 0x53, 0xd9, 0x76, 0x9e, 0x9a, 0xb7, 0x80, 0x63,
	0xb7, 0xc0, 0xc1, 0x07, 0x97, 0xae, 0xaa, 0xdf, 0x36, 0xa8, 0x35, 0x7d, 0x1b, 0x36, 0xb1, 0xc7,
	0xe0, 0x1a, 0xa2, 0x66, 0x4f, 0xcf, 0xd7, 0xe5, 0x66, 0x69, 0xed, 0x37, 0xcb, 0x71, 0x3e, 0x93,
	0xda, 0x93, 0xfa, 0xb4, 0x93, 0x0f, 0xa1, 0x87, 0x3b, 0xe4, 0x73, 0x35, 0x83, 0x2d, 0xaa, 0x3d,
	0xd6, 0x22, 0x19, 0xa0, 0xdc, 0x88, 0xb5, 0x44, 0xf6, 0x00, 0x1a, 0x8a, 0xdf, 0xf4, 0x5c, 0x7b,
	0x64, 0x91, 0xd5, 0x3f, 0x85, 0x7e, 0x26, 0xa9, 0x59, 0xf8, 0x43, 0x68, 0x2a, 0x87, 0xf4, 0x9c,
	0xd2, 0x88, 0xd3, 0x66, 0x4a, 0x9f, 0x48, 0xc3, 0x38, 0x4b, 0x92, 0x5e, 0xf8, 0xdf, 0xc3, 0xc0,
	0xa8, 0x64, 0x76, 0x4e, 0x31, 0x2b, 0x9d, 0xdb, 0x67, 0x65, 0xc5, 0x49, 0xdf, 0x00, 0xcb, 0x07,
	0x68, 0x71, 0x5a, 0x31, 0xa0, 0x9d, 0x03, 0x03, 0xfa, 0xd9, 0x3f, 0x4d, 0x3d, 0x6d, 0x5e, 0x63,
	0x72, 0xad, 0x2a, 0xf0, 0x49, 0xf6, 0x33, 0x37, 0xcc, 0x2f, 0xd7, 0x24, 0x18, 0x8f, 0x0a, 0x43,
	0x76, 0xc3, 0x17, 0x30, 0x7c, 0x95, 0x60, 0x98, 0x22, 0x8d, 0x23, 0xda, 0x45, 0x41, 0xf6, 0x74,
	0xba, 0x65, 0xdb, 0x53, 0x70, 0x8d, 0x20, 0xb3, 0x3b, 0xca, 0x5b, 0x92, 0xe7, 0x5b, 0xb6, 0x7c,
	0x09, 0x50, 0x48, 0x01, 0x7b, 0x8f, 0x2e, 0x29, 0x4b, 0xc3, 0xf8, 0xc8, 0x6c, 0x2b, 0x72, 0xf0,
	0x35, 0x74, 0xad, 0xce, 0x65, 0xc7, 0xc5, 0x46, 0x9b, 0xdf, 0x63, 0xa6, 0xec, 0xa5, 0x62, 0x3c,
	0x86, 0x26, 0x9d, 0xc5, 0x46, 0xd6, 0xb1, 0x95, 0x17, 0xbd, 0x80, 0xe1, 0x77, 0x98, 0x9e, 0xdb,
	0x8a, 0x77, 0x3c, 0xd3, 0x3f, 0xd5, 0x33, 0xf3, 0x53, 0x3d, 0x3b, 0x55, 0x3f, 0xd5, 0xe3, 0xe3,
	0x9d, 0x3a, 0xd8, 0x58, 0x07, 0xca, 0xfa, 0x4a, 0xb7, 0x08, 0x47, 0xb9, 0x5f, 0x02, 0xda, 0x5a,
	0x04, 0xe4, 0x5b, 0xbf, 0x85, 0x91, 0x69, 0xfd, 0xcc, 0x7b, 0xa3, 0x33, 0x5b, 0x12, 0x84, 0xca,
	0x03, 0x5e, 0x68, 0x06, 0x9d, 0xaf, 0x2f, 0xdf, 0xf9, 0x88, 0x0c, 0xfe, 0x59, 0xde, 0x55, 0x15,
	0xf0, 0x8b, 0x80, 0x7c, 0xeb, 0x73, 0x00, 0x15, 0xa6, 0x0b, 0xc0, 0x8e, 0xec, 0x62, 0x54, 0xd7,
	0xe7, 0x2b, 0xe8, 0x5a, 0x4a, 0xa5, 0x4b, 0xbb, 0x2f, 0x5d, 0xfb, 0x5c, 0xba, 0x6c, 0x51, 0x3d,
	0x9e, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x24, 0x84, 0xdd, 0x1a, 0x04, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	Item(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	CreateDraftItem(ctx context.Context, in *DraftRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	EditItem(ctx context.Context, in *EditItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*ItemsResponse, error)
	DeleteOffer(ctx context.Context, in *DeleteOfferRequest, opts ...grpc.CallOption) (*OffersResponse, error)
	Items(ctx context.Context, in *ItemsRequest, opts ...grpc.CallOption) (*ItemsResponse, error)
	GetUploadImages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ItemImagesResponse, error)
	ItemCategories(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*CategoriesResponse, error)
	ItemBindCategory(ctx context.Context, in *ItemBindRequest, opts ...grpc.CallOption) (*CategoriesResponse, error)
	ItemUnbindCategory(ctx context.Context, in *ItemBindRequest, opts ...grpc.CallOption) (*CategoriesResponse, error)
	ItemProperties(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*PropertiesResponse, error)
	ItemOffers(ctx context.Context, in *OffersRequest, opts ...grpc.CallOption) (*OffersResponse, error)
	UploadOffer(ctx context.Context, in *UploadOfferRequest, opts ...grpc.CallOption) (*ItemResponse, error)
}

type itemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemServiceClient(cc grpc.ClientConnInterface) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) Item(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/Item", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateDraftItem(ctx context.Context, in *DraftRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/CreateDraftItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) EditItem(ctx context.Context, in *EditItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/EditItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*ItemsResponse, error) {
	out := new(ItemsResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteOffer(ctx context.Context, in *DeleteOfferRequest, opts ...grpc.CallOption) (*OffersResponse, error) {
	out := new(OffersResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/DeleteOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Items(ctx context.Context, in *ItemsRequest, opts ...grpc.CallOption) (*ItemsResponse, error) {
	out := new(ItemsResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/Items", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetUploadImages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ItemImagesResponse, error) {
	out := new(ItemImagesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/GetUploadImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemCategories(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/ItemCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemBindCategory(ctx context.Context, in *ItemBindRequest, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/ItemBindCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemUnbindCategory(ctx context.Context, in *ItemBindRequest, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/ItemUnbindCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemProperties(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*PropertiesResponse, error) {
	out := new(PropertiesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/ItemProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemOffers(ctx context.Context, in *OffersRequest, opts ...grpc.CallOption) (*OffersResponse, error) {
	out := new(OffersResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/ItemOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) UploadOffer(ctx context.Context, in *UploadOfferRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/UploadOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	Item(context.Context, *ItemRequest) (*ItemResponse, error)
	CreateDraftItem(context.Context, *DraftRequest) (*ItemResponse, error)
	EditItem(context.Context, *EditItemRequest) (*ItemResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*ItemsResponse, error)
	DeleteOffer(context.Context, *DeleteOfferRequest) (*OffersResponse, error)
	Items(context.Context, *ItemsRequest) (*ItemsResponse, error)
	GetUploadImages(context.Context, *empty.Empty) (*ItemImagesResponse, error)
	ItemCategories(context.Context, *ItemRequest) (*CategoriesResponse, error)
	ItemBindCategory(context.Context, *ItemBindRequest) (*CategoriesResponse, error)
	ItemUnbindCategory(context.Context, *ItemBindRequest) (*CategoriesResponse, error)
	ItemProperties(context.Context, *ItemRequest) (*PropertiesResponse, error)
	ItemOffers(context.Context, *OffersRequest) (*OffersResponse, error)
	UploadOffer(context.Context, *UploadOfferRequest) (*ItemResponse, error)
}

// UnimplementedItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (*UnimplementedItemServiceServer) Item(ctx context.Context, req *ItemRequest) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Item not implemented")
}
func (*UnimplementedItemServiceServer) CreateDraftItem(ctx context.Context, req *DraftRequest) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDraftItem not implemented")
}
func (*UnimplementedItemServiceServer) EditItem(ctx context.Context, req *EditItemRequest) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditItem not implemented")
}
func (*UnimplementedItemServiceServer) DeleteItem(ctx context.Context, req *DeleteItemRequest) (*ItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (*UnimplementedItemServiceServer) DeleteOffer(ctx context.Context, req *DeleteOfferRequest) (*OffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOffer not implemented")
}
func (*UnimplementedItemServiceServer) Items(ctx context.Context, req *ItemsRequest) (*ItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Items not implemented")
}
func (*UnimplementedItemServiceServer) GetUploadImages(ctx context.Context, req *empty.Empty) (*ItemImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadImages not implemented")
}
func (*UnimplementedItemServiceServer) ItemCategories(ctx context.Context, req *ItemRequest) (*CategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemCategories not implemented")
}
func (*UnimplementedItemServiceServer) ItemBindCategory(ctx context.Context, req *ItemBindRequest) (*CategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemBindCategory not implemented")
}
func (*UnimplementedItemServiceServer) ItemUnbindCategory(ctx context.Context, req *ItemBindRequest) (*CategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemUnbindCategory not implemented")
}
func (*UnimplementedItemServiceServer) ItemProperties(ctx context.Context, req *ItemRequest) (*PropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemProperties not implemented")
}
func (*UnimplementedItemServiceServer) ItemOffers(ctx context.Context, req *OffersRequest) (*OffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemOffers not implemented")
}
func (*UnimplementedItemServiceServer) UploadOffer(ctx context.Context, req *UploadOfferRequest) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadOffer not implemented")
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_Item_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Item(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/Item",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Item(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateDraftItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateDraftItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/CreateDraftItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateDraftItem(ctx, req.(*DraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_EditItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).EditItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/EditItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).EditItem(ctx, req.(*EditItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/DeleteOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteOffer(ctx, req.(*DeleteOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Items_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Items(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/Items",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Items(ctx, req.(*ItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_GetUploadImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetUploadImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/GetUploadImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetUploadImages(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/ItemCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemCategories(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemBindCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemBindCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/ItemBindCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemBindCategory(ctx, req.(*ItemBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemUnbindCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemUnbindCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/ItemUnbindCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemUnbindCategory(ctx, req.(*ItemBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/ItemProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemProperties(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/ItemOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemOffers(ctx, req.(*OffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_UploadOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).UploadOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/UploadOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).UploadOffer(ctx, req.(*UploadOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Item",
			Handler:    _ItemService_Item_Handler,
		},
		{
			MethodName: "CreateDraftItem",
			Handler:    _ItemService_CreateDraftItem_Handler,
		},
		{
			MethodName: "EditItem",
			Handler:    _ItemService_EditItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _ItemService_DeleteItem_Handler,
		},
		{
			MethodName: "DeleteOffer",
			Handler:    _ItemService_DeleteOffer_Handler,
		},
		{
			MethodName: "Items",
			Handler:    _ItemService_Items_Handler,
		},
		{
			MethodName: "GetUploadImages",
			Handler:    _ItemService_GetUploadImages_Handler,
		},
		{
			MethodName: "ItemCategories",
			Handler:    _ItemService_ItemCategories_Handler,
		},
		{
			MethodName: "ItemBindCategory",
			Handler:    _ItemService_ItemBindCategory_Handler,
		},
		{
			MethodName: "ItemUnbindCategory",
			Handler:    _ItemService_ItemUnbindCategory_Handler,
		},
		{
			MethodName: "ItemProperties",
			Handler:    _ItemService_ItemProperties_Handler,
		},
		{
			MethodName: "ItemOffers",
			Handler:    _ItemService_ItemOffers_Handler,
		},
		{
			MethodName: "UploadOffer",
			Handler:    _ItemService_UploadOffer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}
