// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32       `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VendorId             uint32       `protobuf:"varint,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ParentId             uint32       `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CategoryId           uint32       `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Title                string       `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Article              string       `protobuf:"bytes,7,opt,name=article,proto3" json:"article,omitempty"`
	Alias                string       `protobuf:"bytes,8,opt,name=alias,proto3" json:"alias,omitempty"`
	Description          string       `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32      `protobuf:"fixed32,10,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice             float32      `protobuf:"fixed32,11,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	CurrencyId           uint32       `protobuf:"varint,12,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Count                int32        `protobuf:"varint,13,opt,name=count,proto3" json:"count,omitempty"`
	Disable              bool         `protobuf:"varint,14,opt,name=disable,proto3" json:"disable,omitempty"`
	Sort                 uint32       `protobuf:"varint,15,opt,name=sort,proto3" json:"sort,omitempty"`
	SeoTitle             string       `protobuf:"bytes,16,opt,name=seo_title,json=seoTitle,proto3" json:"seo_title,omitempty"`
	SeoDescription       string       `protobuf:"bytes,17,opt,name=seo_description,json=seoDescription,proto3" json:"seo_description,omitempty"`
	SeoKeywords          string       `protobuf:"bytes,18,opt,name=seo_keywords,json=seoKeywords,proto3" json:"seo_keywords,omitempty"`
	Images               []*ItemImage `protobuf:"bytes,19,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Item) GetVendorId() uint32 {
	if m != nil {
		return m.VendorId
	}
	return 0
}

func (m *Item) GetParentId() uint32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Item) GetCategoryId() uint32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *Item) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetOldPrice() float32 {
	if m != nil {
		return m.OldPrice
	}
	return 0
}

func (m *Item) GetCurrencyId() uint32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *Item) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Item) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

func (m *Item) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *Item) GetSeoTitle() string {
	if m != nil {
		return m.SeoTitle
	}
	return ""
}

func (m *Item) GetSeoDescription() string {
	if m != nil {
		return m.SeoDescription
	}
	return ""
}

func (m *Item) GetSeoKeywords() string {
	if m != nil {
		return m.SeoKeywords
	}
	return ""
}

func (m *Item) GetImages() []*ItemImage {
	if m != nil {
		return m.Images
	}
	return nil
}

type ItemImage struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               uint32   `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Filename             string   `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Sort                 uint32   `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	PropertyValueId      uint32   `protobuf:"varint,6,opt,name=property_value_id,json=propertyValueId,proto3" json:"property_value_id,omitempty"`
	Main                 bool     `protobuf:"varint,7,opt,name=main,proto3" json:"main,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemImage) Reset()         { *m = ItemImage{} }
func (m *ItemImage) String() string { return proto.CompactTextString(m) }
func (*ItemImage) ProtoMessage()    {}
func (*ItemImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *ItemImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemImage.Unmarshal(m, b)
}
func (m *ItemImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemImage.Marshal(b, m, deterministic)
}
func (m *ItemImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemImage.Merge(m, src)
}
func (m *ItemImage) XXX_Size() int {
	return xxx_messageInfo_ItemImage.Size(m)
}
func (m *ItemImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemImage.DiscardUnknown(m)
}

var xxx_messageInfo_ItemImage proto.InternalMessageInfo

func (m *ItemImage) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ItemImage) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ItemImage) GetItemId() uint32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ItemImage) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ItemImage) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *ItemImage) GetPropertyValueId() uint32 {
	if m != nil {
		return m.PropertyValueId
	}
	return 0
}

func (m *ItemImage) GetMain() bool {
	if m != nil {
		return m.Main
	}
	return false
}

type ItemProperty struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	PropertyValueIds     []uint32 `protobuf:"varint,2,rep,packed,name=property_value_ids,json=propertyValueIds,proto3" json:"property_value_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemProperty) Reset()         { *m = ItemProperty{} }
func (m *ItemProperty) String() string { return proto.CompactTextString(m) }
func (*ItemProperty) ProtoMessage()    {}
func (*ItemProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *ItemProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemProperty.Unmarshal(m, b)
}
func (m *ItemProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemProperty.Marshal(b, m, deterministic)
}
func (m *ItemProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemProperty.Merge(m, src)
}
func (m *ItemProperty) XXX_Size() int {
	return xxx_messageInfo_ItemProperty.Size(m)
}
func (m *ItemProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemProperty.DiscardUnknown(m)
}

var xxx_messageInfo_ItemProperty proto.InternalMessageInfo

func (m *ItemProperty) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ItemProperty) GetPropertyValueIds() []uint32 {
	if m != nil {
		return m.PropertyValueIds
	}
	return nil
}

type ItemRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRequest) Reset()         { *m = ItemRequest{} }
func (m *ItemRequest) String() string { return proto.CompactTextString(m) }
func (*ItemRequest) ProtoMessage()    {}
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *ItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRequest.Unmarshal(m, b)
}
func (m *ItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRequest.Marshal(b, m, deterministic)
}
func (m *ItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRequest.Merge(m, src)
}
func (m *ItemRequest) XXX_Size() int {
	return xxx_messageInfo_ItemRequest.Size(m)
}
func (m *ItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRequest proto.InternalMessageInfo

func (m *ItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ItemsRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsRequest) Reset()         { *m = ItemsRequest{} }
func (m *ItemsRequest) String() string { return proto.CompactTextString(m) }
func (*ItemsRequest) ProtoMessage()    {}
func (*ItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{4}
}

func (m *ItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsRequest.Unmarshal(m, b)
}
func (m *ItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsRequest.Marshal(b, m, deterministic)
}
func (m *ItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsRequest.Merge(m, src)
}
func (m *ItemsRequest) XXX_Size() int {
	return xxx_messageInfo_ItemsRequest.Size(m)
}
func (m *ItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsRequest proto.InternalMessageInfo

func (m *ItemsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ItemsRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ItemsRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ItemsRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type EditItemRequest struct {
	Id                   uint32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Article              string          `protobuf:"bytes,3,opt,name=article,proto3" json:"article,omitempty"`
	Alias                string          `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	Count                int32           `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Description          string          `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32         `protobuf:"fixed32,7,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice             float32         `protobuf:"fixed32,8,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	CurrencyId           uint32          `protobuf:"varint,9,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Disable              bool            `protobuf:"varint,10,opt,name=disable,proto3" json:"disable,omitempty"`
	Sort                 uint32          `protobuf:"varint,11,opt,name=sort,proto3" json:"sort,omitempty"`
	ItemImages           []uint32        `protobuf:"varint,12,rep,packed,name=item_images,json=itemImages,proto3" json:"item_images,omitempty"`
	UploadImages         []uint32        `protobuf:"varint,13,rep,packed,name=upload_images,json=uploadImages,proto3" json:"upload_images,omitempty"`
	Properties           []*ItemProperty `protobuf:"bytes,14,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EditItemRequest) Reset()         { *m = EditItemRequest{} }
func (m *EditItemRequest) String() string { return proto.CompactTextString(m) }
func (*EditItemRequest) ProtoMessage()    {}
func (*EditItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{5}
}

func (m *EditItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditItemRequest.Unmarshal(m, b)
}
func (m *EditItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditItemRequest.Marshal(b, m, deterministic)
}
func (m *EditItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditItemRequest.Merge(m, src)
}
func (m *EditItemRequest) XXX_Size() int {
	return xxx_messageInfo_EditItemRequest.Size(m)
}
func (m *EditItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditItemRequest proto.InternalMessageInfo

func (m *EditItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditItemRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditItemRequest) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *EditItemRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *EditItemRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *EditItemRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditItemRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *EditItemRequest) GetOldPrice() float32 {
	if m != nil {
		return m.OldPrice
	}
	return 0
}

func (m *EditItemRequest) GetCurrencyId() uint32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *EditItemRequest) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

func (m *EditItemRequest) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *EditItemRequest) GetItemImages() []uint32 {
	if m != nil {
		return m.ItemImages
	}
	return nil
}

func (m *EditItemRequest) GetUploadImages() []uint32 {
	if m != nil {
		return m.UploadImages
	}
	return nil
}

func (m *EditItemRequest) GetProperties() []*ItemProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

type DeleteItemRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemRequest) Reset()         { *m = DeleteItemRequest{} }
func (m *DeleteItemRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteItemRequest) ProtoMessage()    {}
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{6}
}

func (m *DeleteItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemRequest.Unmarshal(m, b)
}
func (m *DeleteItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemRequest.Marshal(b, m, deterministic)
}
func (m *DeleteItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemRequest.Merge(m, src)
}
func (m *DeleteItemRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteItemRequest.Size(m)
}
func (m *DeleteItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemRequest proto.InternalMessageInfo

func (m *DeleteItemRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteItemRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *DeleteItemRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *DeleteItemRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *DeleteItemRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type ItemBindRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId           string   `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemBindRequest) Reset()         { *m = ItemBindRequest{} }
func (m *ItemBindRequest) String() string { return proto.CompactTextString(m) }
func (*ItemBindRequest) ProtoMessage()    {}
func (*ItemBindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{7}
}

func (m *ItemBindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemBindRequest.Unmarshal(m, b)
}
func (m *ItemBindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemBindRequest.Marshal(b, m, deterministic)
}
func (m *ItemBindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemBindRequest.Merge(m, src)
}
func (m *ItemBindRequest) XXX_Size() int {
	return xxx_messageInfo_ItemBindRequest.Size(m)
}
func (m *ItemBindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemBindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemBindRequest proto.InternalMessageInfo

func (m *ItemBindRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ItemBindRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

type ItemResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemResponse) Reset()         { *m = ItemResponse{} }
func (m *ItemResponse) String() string { return proto.CompactTextString(m) }
func (*ItemResponse) ProtoMessage()    {}
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{8}
}

func (m *ItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemResponse.Unmarshal(m, b)
}
func (m *ItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemResponse.Marshal(b, m, deterministic)
}
func (m *ItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemResponse.Merge(m, src)
}
func (m *ItemResponse) XXX_Size() int {
	return xxx_messageInfo_ItemResponse.Size(m)
}
func (m *ItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemResponse proto.InternalMessageInfo

func (m *ItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type ItemsResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsResponse) Reset()         { *m = ItemsResponse{} }
func (m *ItemsResponse) String() string { return proto.CompactTextString(m) }
func (*ItemsResponse) ProtoMessage()    {}
func (*ItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{9}
}

func (m *ItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsResponse.Unmarshal(m, b)
}
func (m *ItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsResponse.Marshal(b, m, deterministic)
}
func (m *ItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsResponse.Merge(m, src)
}
func (m *ItemsResponse) XXX_Size() int {
	return xxx_messageInfo_ItemsResponse.Size(m)
}
func (m *ItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsResponse proto.InternalMessageInfo

func (m *ItemsResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ItemsResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ItemImagesResponse struct {
	Images               []*ItemImage `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ItemImagesResponse) Reset()         { *m = ItemImagesResponse{} }
func (m *ItemImagesResponse) String() string { return proto.CompactTextString(m) }
func (*ItemImagesResponse) ProtoMessage()    {}
func (*ItemImagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{10}
}

func (m *ItemImagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemImagesResponse.Unmarshal(m, b)
}
func (m *ItemImagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemImagesResponse.Marshal(b, m, deterministic)
}
func (m *ItemImagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemImagesResponse.Merge(m, src)
}
func (m *ItemImagesResponse) XXX_Size() int {
	return xxx_messageInfo_ItemImagesResponse.Size(m)
}
func (m *ItemImagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemImagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemImagesResponse proto.InternalMessageInfo

func (m *ItemImagesResponse) GetImages() []*ItemImage {
	if m != nil {
		return m.Images
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "v1.Item")
	proto.RegisterType((*ItemImage)(nil), "v1.ItemImage")
	proto.RegisterType((*ItemProperty)(nil), "v1.ItemProperty")
	proto.RegisterType((*ItemRequest)(nil), "v1.ItemRequest")
	proto.RegisterType((*ItemsRequest)(nil), "v1.ItemsRequest")
	proto.RegisterType((*EditItemRequest)(nil), "v1.EditItemRequest")
	proto.RegisterType((*DeleteItemRequest)(nil), "v1.DeleteItemRequest")
	proto.RegisterType((*ItemBindRequest)(nil), "v1.ItemBindRequest")
	proto.RegisterType((*ItemResponse)(nil), "v1.ItemResponse")
	proto.RegisterType((*ItemsResponse)(nil), "v1.ItemsResponse")
	proto.RegisterType((*ItemImagesResponse)(nil), "v1.ItemImagesResponse")
}

func init() {
	proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df)
}

var fileDescriptor_6007f868cf6553df = []byte{
	// 916 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5d, 0x8f, 0xdb, 0x44,
	0x14, 0x95, 0x13, 0x27, 0x71, 0x6e, 0x3e, 0x77, 0x0a, 0xad, 0x95, 0x16, 0x1a, 0x8c, 0x10, 0x01,
	0xad, 0x52, 0x76, 0x91, 0x90, 0x10, 0x0f, 0xa8, 0xa5, 0x2b, 0x14, 0xf1, 0xb2, 0x72, 0x29, 0xaf,
	0x91, 0x37, 0x73, 0x1b, 0x8d, 0x70, 0x3c, 0xae, 0xc7, 0x09, 0xda, 0xfe, 0x00, 0x1e, 0x79, 0x87,
	0xff, 0xc2, 0x7f, 0x43, 0x73, 0xc7, 0x63, 0x9b, 0xa4, 0xce, 0x43, 0xdf, 0x7c, 0xcf, 0xb9, 0x33,
	0xbe, 0x39, 0x73, 0xce, 0xc4, 0x00, 0x22, 0xc7, 0xdd, 0x32, 0xcd, 0x64, 0x2e, 0x59, 0xeb, 0x70,
	0x35, 0x7b, 0xbc, 0x95, 0x72, 0x1b, 0xe3, 0x33, 0x42, 0xee, 0xf6, 0x6f, 0x9e, 0xe1, 0x2e, 0xcd,
	0xef, 0x4d, 0xc3, 0x6c, 0xbc, 0x89, 0x72, 0xdc, 0xca, 0xac, 0xac, 0xd3, 0x4c, 0xa6, 0x98, 0x59,
	0x3e, 0xf8, 0xc7, 0x05, 0x77, 0x95, 0xe3, 0x8e, 0x8d, 0xa1, 0x25, 0xb8, 0xef, 0xcc, 0x9d, 0x45,
	0x3f, 0x6c, 0x09, 0xce, 0x1e, 0x41, 0x6f, 0xaf, 0x30, 0x5b, 0x0b, 0xee, 0xb7, 0xe6, 0xce, 0x62,
	0x14, 0x76, 0x75, 0xb9, 0xe2, 0xec, 0x31, 0xf4, 0x0f, 0x98, 0x70, 0x49, 0x54, 0x9b, 0x28, 0xcf,
	0x00, 0x86, 0x4c, 0xa3, 0x0c, 0x93, 0x5c, 0x93, 0xae, 0x21, 0x0d, 0xb0, 0xe2, 0xec, 0x29, 0x0c,
	0xec, 0x34, 0x9a, 0xee, 0x10, 0x0d, 0x16, 0x5a, 0x71, 0xf6, 0x11, 0x74, 0x72, 0x91, 0xc7, 0xe8,
	0x77, 0x69, 0x0c, 0x53, 0x30, 0x1f, 0x7a, 0x51, 0x96, 0x8b, 0x4d, 0x8c, 0x7e, 0x8f, 0x70, 0x5b,
	0xea, 0xfe, 0x28, 0x16, 0x91, 0xf2, 0x3d, 0xd3, 0x4f, 0x05, 0x9b, 0xc3, 0x80, 0xa3, 0xda, 0x64,
	0x22, 0xcd, 0x85, 0x4c, 0xfc, 0x3e, 0x71, 0x75, 0x48, 0xaf, 0x4b, 0x33, 0xb1, 0x41, 0x1f, 0xe6,
	0xce, 0xa2, 0x15, 0x9a, 0x42, 0xcf, 0x2e, 0x63, 0xbe, 0x36, 0xcc, 0x80, 0x18, 0x4f, 0xc6, 0xfc,
	0x96, 0x48, 0x3d, 0xfb, 0x3e, 0xcb, 0x30, 0xd9, 0xd0, 0xec, 0xc3, 0x62, 0xf6, 0x02, 0x32, 0xb3,
	0x6f, 0xe4, 0x3e, 0xc9, 0xfd, 0xd1, 0xdc, 0x59, 0x74, 0x42, 0x53, 0xe8, 0xd9, 0xb9, 0x50, 0xd1,
	0x5d, 0x8c, 0xfe, 0x78, 0xee, 0x2c, 0xbc, 0xd0, 0x96, 0x8c, 0x81, 0xab, 0x64, 0x96, 0xfb, 0x13,
	0xda, 0x89, 0x9e, 0xf5, 0x04, 0x0a, 0xe5, 0xda, 0x68, 0x30, 0xa5, 0xb9, 0x3d, 0x85, 0xf2, 0x57,
	0x92, 0xe1, 0x4b, 0x98, 0x68, 0xb2, 0xfe, 0xd3, 0x2e, 0xa8, 0x65, 0xac, 0x50, 0xbe, 0xac, 0xfd,
	0xba, 0xcf, 0x60, 0xa8, 0x1b, 0x7f, 0xc7, 0xfb, 0x3f, 0x64, 0xc6, 0x95, 0xcf, 0x8c, 0x00, 0x0a,
	0xe5, 0x2f, 0x05, 0xc4, 0xbe, 0x80, 0xae, 0xd8, 0x45, 0x5b, 0x54, 0xfe, 0x83, 0x79, 0x7b, 0x31,
	0xb8, 0x1e, 0x2d, 0x0f, 0x57, 0x4b, 0x6d, 0x83, 0x95, 0x46, 0xc3, 0x82, 0x0c, 0xfe, 0x75, 0xa0,
	0x5f, 0xa2, 0x35, 0x87, 0x8c, 0xce, 0x3b, 0xe4, 0x11, 0xf4, 0xb4, 0x45, 0x2b, 0x7f, 0x74, 0x75,
	0xb9, 0xe2, 0x6c, 0x06, 0xde, 0x1b, 0x11, 0x63, 0x12, 0xed, 0x90, 0xcc, 0xd1, 0x0f, 0xcb, 0xba,
	0xd4, 0xa3, 0x53, 0xd3, 0xe3, 0x6b, 0xb8, 0xb0, 0x76, 0x5d, 0x1f, 0xa2, 0x78, 0x8f, 0x7a, 0xcb,
	0x2e, 0x35, 0x4c, 0x2c, 0xf1, 0x9b, 0xc6, 0x57, 0x5c, 0xaf, 0xdf, 0x45, 0x22, 0x21, 0x8b, 0x78,
	0x21, 0x3d, 0x07, 0xb7, 0x30, 0xd4, 0xe3, 0xdf, 0x16, 0xad, 0xba, 0x67, 0x23, 0x39, 0x16, 0x2e,
	0xa7, 0x67, 0x76, 0x09, 0xec, 0xe4, 0x1d, 0xca, 0x6f, 0xcd, 0xdb, 0x8b, 0x51, 0x38, 0x3d, 0x7a,
	0x89, 0x0a, 0x3e, 0x81, 0x81, 0xde, 0x31, 0xc4, 0xb7, 0x7b, 0x54, 0xf9, 0xb1, 0x24, 0xc1, 0x5b,
	0xf3, 0x42, 0x65, 0x79, 0x06, 0x6e, 0x1a, 0x6d, 0xb1, 0xe8, 0xa0, 0x67, 0x13, 0x91, 0x2d, 0xae,
	0x95, 0x78, 0x87, 0x85, 0x70, 0x9e, 0x06, 0x5e, 0x89, 0x77, 0x95, 0x0a, 0x6d, 0x33, 0x21, 0xa9,
	0xf0, 0x04, 0xfa, 0x5c, 0x64, 0xb8, 0xa1, 0x23, 0x37, 0xb2, 0x55, 0x40, 0xf0, 0x77, 0x1b, 0x26,
	0x37, 0x5c, 0xe4, 0x67, 0xc6, 0xaa, 0x72, 0xd5, 0x6a, 0xc8, 0x55, 0xbb, 0x21, 0x57, 0x6e, 0x3d,
	0x57, 0xa5, 0xc3, 0x3b, 0x75, 0x87, 0x1f, 0xa5, 0xad, 0x7b, 0x26, 0x6d, 0xbd, 0xc6, 0xb4, 0x79,
	0xe7, 0xd3, 0xd6, 0x3f, 0x49, 0x5b, 0x2d, 0x57, 0xf0, 0xfe, 0x5c, 0x0d, 0x6a, 0x3e, 0x7a, 0x0a,
	0x03, 0x63, 0x48, 0xe3, 0xf9, 0x21, 0x1d, 0x2e, 0x5d, 0xa3, 0xe4, 0x6c, 0xc5, 0x3e, 0x87, 0xd1,
	0x3e, 0x8d, 0x65, 0xc4, 0x6d, 0xcb, 0x88, 0x5a, 0x86, 0x06, 0x2c, 0x9a, 0xbe, 0x01, 0x28, 0xfc,
	0x20, 0x50, 0xf9, 0x63, 0x0a, 0xce, 0xd4, 0x06, 0xc7, 0x7a, 0x2c, 0xac, 0xf5, 0x04, 0x7f, 0x3a,
	0x70, 0xf1, 0x12, 0x63, 0xcc, 0xf1, 0xdc, 0xe9, 0x58, 0x93, 0xb4, 0x9a, 0x4c, 0xd2, 0x6e, 0x30,
	0x89, 0xdb, 0x64, 0x92, 0xce, 0xb1, 0x49, 0x5e, 0xc0, 0x44, 0x4f, 0xf0, 0x42, 0x24, 0xbc, 0x69,
	0x8a, 0xa3, 0xcb, 0xd9, 0x38, 0xa5, 0x76, 0x39, 0x07, 0x97, 0xc6, 0xdb, 0x21, 0xaa, 0x54, 0x26,
	0x0a, 0xd9, 0x13, 0x70, 0xb5, 0x82, 0xb4, 0xc5, 0xe0, 0xda, 0xb3, 0x42, 0x84, 0x84, 0x06, 0x37,
	0x30, 0x2a, 0x92, 0x50, 0xb4, 0x7f, 0x0a, 0x1d, 0x4d, 0x28, 0xdf, 0x21, 0xe1, 0xaa, 0x7e, 0x03,
	0x93, 0x47, 0x65, 0x1e, 0xc5, 0x85, 0x0c, 0xa6, 0x08, 0x7e, 0x00, 0x56, 0x5e, 0x40, 0xd5, 0x5e,
	0xd5, 0xf5, 0xe5, 0x9c, 0xb9, 0xbe, 0xae, 0xff, 0x72, 0x4d, 0x5a, 0x5f, 0x61, 0x76, 0xd0, 0xae,
	0xfa, 0xaa, 0xf8, 0xab, 0x9b, 0x94, 0xef, 0x36, 0x5a, 0xcc, 0xa6, 0x15, 0x50, 0xbc, 0xe1, 0x0a,
	0x3c, 0x1b, 0x2a, 0xf6, 0x40, 0xb3, 0x47, 0x11, 0x7b, 0xcf, 0x92, 0xef, 0x00, 0xaa, 0xb3, 0x66,
	0x1f, 0x6b, 0xfe, 0xe4, 0xec, 0x67, 0x17, 0x76, 0x59, 0xf5, 0x63, 0x2e, 0xa1, 0x43, 0x00, 0x9b,
	0xd6, 0xb8, 0xc6, 0xee, 0xe7, 0x30, 0xf9, 0x19, 0xf3, 0xd7, 0x75, 0x5f, 0x3e, 0x5c, 0x9a, 0x0f,
	0x80, 0xa5, 0xfd, 0x00, 0x58, 0xde, 0xe8, 0x0f, 0x80, 0xd9, 0xc3, 0xff, 0xa9, 0x52, 0x6d, 0xf1,
	0x3d, 0x8c, 0x35, 0xfa, 0x93, 0x39, 0x5a, 0x81, 0xea, 0x54, 0x10, 0x5a, 0x5a, 0x35, 0x94, 0x4b,
	0x7f, 0x84, 0xa9, 0xf5, 0x51, 0xc1, 0xde, 0x1b, 0x79, 0x8e, 0xdc, 0xd5, 0xb8, 0xc1, 0x73, 0x73,
	0x9e, 0xaf, 0x93, 0xbb, 0x0f, 0xde, 0xa2, 0x18, 0xff, 0xb6, 0x8c, 0x59, 0xc3, 0xf8, 0x55, 0x83,
	0x5d, 0x7a, 0xd7, 0x25, 0x85, 0xbe, 0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x7e, 0x02, 0x35,
	0x42, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	Item(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	EditItem(ctx context.Context, in *EditItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*ItemsResponse, error)
	Items(ctx context.Context, in *ItemsRequest, opts ...grpc.CallOption) (*ItemsResponse, error)
	GetUploadImages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ItemImagesResponse, error)
	ItemCategories(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*CategoriesResponse, error)
	ItemBindCategory(ctx context.Context, in *ItemBindRequest, opts ...grpc.CallOption) (*CategoriesResponse, error)
	ItemUnbindCategory(ctx context.Context, in *ItemBindRequest, opts ...grpc.CallOption) (*CategoriesResponse, error)
	ItemProperties(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*PropertiesResponse, error)
}

type itemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemServiceClient(cc grpc.ClientConnInterface) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) Item(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/Item", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) EditItem(ctx context.Context, in *EditItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/EditItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*ItemsResponse, error) {
	out := new(ItemsResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Items(ctx context.Context, in *ItemsRequest, opts ...grpc.CallOption) (*ItemsResponse, error) {
	out := new(ItemsResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/Items", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetUploadImages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ItemImagesResponse, error) {
	out := new(ItemImagesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/GetUploadImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemCategories(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/ItemCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemBindCategory(ctx context.Context, in *ItemBindRequest, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/ItemBindCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemUnbindCategory(ctx context.Context, in *ItemBindRequest, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/ItemUnbindCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ItemProperties(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*PropertiesResponse, error) {
	out := new(PropertiesResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/ItemProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	Item(context.Context, *ItemRequest) (*ItemResponse, error)
	EditItem(context.Context, *EditItemRequest) (*ItemResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*ItemsResponse, error)
	Items(context.Context, *ItemsRequest) (*ItemsResponse, error)
	GetUploadImages(context.Context, *empty.Empty) (*ItemImagesResponse, error)
	ItemCategories(context.Context, *ItemRequest) (*CategoriesResponse, error)
	ItemBindCategory(context.Context, *ItemBindRequest) (*CategoriesResponse, error)
	ItemUnbindCategory(context.Context, *ItemBindRequest) (*CategoriesResponse, error)
	ItemProperties(context.Context, *ItemRequest) (*PropertiesResponse, error)
}

// UnimplementedItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (*UnimplementedItemServiceServer) Item(ctx context.Context, req *ItemRequest) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Item not implemented")
}
func (*UnimplementedItemServiceServer) EditItem(ctx context.Context, req *EditItemRequest) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditItem not implemented")
}
func (*UnimplementedItemServiceServer) DeleteItem(ctx context.Context, req *DeleteItemRequest) (*ItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (*UnimplementedItemServiceServer) Items(ctx context.Context, req *ItemsRequest) (*ItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Items not implemented")
}
func (*UnimplementedItemServiceServer) GetUploadImages(ctx context.Context, req *empty.Empty) (*ItemImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadImages not implemented")
}
func (*UnimplementedItemServiceServer) ItemCategories(ctx context.Context, req *ItemRequest) (*CategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemCategories not implemented")
}
func (*UnimplementedItemServiceServer) ItemBindCategory(ctx context.Context, req *ItemBindRequest) (*CategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemBindCategory not implemented")
}
func (*UnimplementedItemServiceServer) ItemUnbindCategory(ctx context.Context, req *ItemBindRequest) (*CategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemUnbindCategory not implemented")
}
func (*UnimplementedItemServiceServer) ItemProperties(ctx context.Context, req *ItemRequest) (*PropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemProperties not implemented")
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_Item_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Item(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/Item",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Item(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_EditItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).EditItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/EditItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).EditItem(ctx, req.(*EditItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Items_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Items(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/Items",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Items(ctx, req.(*ItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_GetUploadImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetUploadImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/GetUploadImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetUploadImages(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/ItemCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemCategories(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemBindCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemBindCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/ItemBindCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemBindCategory(ctx, req.(*ItemBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemUnbindCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemUnbindCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/ItemUnbindCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemUnbindCategory(ctx, req.(*ItemBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ItemProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ItemProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/ItemProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ItemProperties(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Item",
			Handler:    _ItemService_Item_Handler,
		},
		{
			MethodName: "EditItem",
			Handler:    _ItemService_EditItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _ItemService_DeleteItem_Handler,
		},
		{
			MethodName: "Items",
			Handler:    _ItemService_Items_Handler,
		},
		{
			MethodName: "GetUploadImages",
			Handler:    _ItemService_GetUploadImages_Handler,
		},
		{
			MethodName: "ItemCategories",
			Handler:    _ItemService_ItemCategories_Handler,
		},
		{
			MethodName: "ItemBindCategory",
			Handler:    _ItemService_ItemBindCategory_Handler,
		},
		{
			MethodName: "ItemUnbindCategory",
			Handler:    _ItemService_ItemUnbindCategory_Handler,
		},
		{
			MethodName: "ItemProperties",
			Handler:    _ItemService_ItemProperties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}
