// Code generated by protoc-gen-go. DO NOT EDIT.
// source: property.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Property struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32           `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string           `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Code                 string           `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Type                 uint32           `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Display              uint32           `protobuf:"varint,6,opt,name=display,proto3" json:"display,omitempty"`
	Required             bool             `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	Multiple             bool             `protobuf:"varint,8,opt,name=multiple,proto3" json:"multiple,omitempty"`
	Sort                 uint32           `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	Values               []*PropertyValue `protobuf:"bytes,10,rep,name=values,proto3" json:"values,omitempty"`
	ItemValues           []uint32         `protobuf:"varint,11,rep,packed,name=item_values,json=itemValues,proto3" json:"item_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_c191a4a5f523572b, []int{0}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Property) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Property) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Property) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Property) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Property) GetDisplay() uint32 {
	if m != nil {
		return m.Display
	}
	return 0
}

func (m *Property) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Property) GetMultiple() bool {
	if m != nil {
		return m.Multiple
	}
	return false
}

func (m *Property) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *Property) GetValues() []*PropertyValue {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Property) GetItemValues() []uint32 {
	if m != nil {
		return m.ItemValues
	}
	return nil
}

type PropertyValue struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PropertyId           uint32   `protobuf:"varint,3,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Sort                 uint32   `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertyValue) Reset()         { *m = PropertyValue{} }
func (m *PropertyValue) String() string { return proto.CompactTextString(m) }
func (*PropertyValue) ProtoMessage()    {}
func (*PropertyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c191a4a5f523572b, []int{1}
}

func (m *PropertyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyValue.Unmarshal(m, b)
}
func (m *PropertyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyValue.Marshal(b, m, deterministic)
}
func (m *PropertyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyValue.Merge(m, src)
}
func (m *PropertyValue) XXX_Size() int {
	return xxx_messageInfo_PropertyValue.Size(m)
}
func (m *PropertyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyValue.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyValue proto.InternalMessageInfo

func (m *PropertyValue) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PropertyValue) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PropertyValue) GetPropertyId() uint32 {
	if m != nil {
		return m.PropertyId
	}
	return 0
}

func (m *PropertyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PropertyValue) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PropertyValue) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type PropertyRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertyRequest) Reset()         { *m = PropertyRequest{} }
func (m *PropertyRequest) String() string { return proto.CompactTextString(m) }
func (*PropertyRequest) ProtoMessage()    {}
func (*PropertyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c191a4a5f523572b, []int{2}
}

func (m *PropertyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyRequest.Unmarshal(m, b)
}
func (m *PropertyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyRequest.Marshal(b, m, deterministic)
}
func (m *PropertyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyRequest.Merge(m, src)
}
func (m *PropertyRequest) XXX_Size() int {
	return xxx_messageInfo_PropertyRequest.Size(m)
}
func (m *PropertyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyRequest proto.InternalMessageInfo

func (m *PropertyRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PropertiesRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertiesRequest) Reset()         { *m = PropertiesRequest{} }
func (m *PropertiesRequest) String() string { return proto.CompactTextString(m) }
func (*PropertiesRequest) ProtoMessage()    {}
func (*PropertiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c191a4a5f523572b, []int{3}
}

func (m *PropertiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertiesRequest.Unmarshal(m, b)
}
func (m *PropertiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertiesRequest.Marshal(b, m, deterministic)
}
func (m *PropertiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertiesRequest.Merge(m, src)
}
func (m *PropertiesRequest) XXX_Size() int {
	return xxx_messageInfo_PropertiesRequest.Size(m)
}
func (m *PropertiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropertiesRequest proto.InternalMessageInfo

func (m *PropertiesRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PropertiesRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PropertiesRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *PropertiesRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type PropertyResponse struct {
	Property             *Property `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PropertyResponse) Reset()         { *m = PropertyResponse{} }
func (m *PropertyResponse) String() string { return proto.CompactTextString(m) }
func (*PropertyResponse) ProtoMessage()    {}
func (*PropertyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c191a4a5f523572b, []int{4}
}

func (m *PropertyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyResponse.Unmarshal(m, b)
}
func (m *PropertyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyResponse.Marshal(b, m, deterministic)
}
func (m *PropertyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyResponse.Merge(m, src)
}
func (m *PropertyResponse) XXX_Size() int {
	return xxx_messageInfo_PropertyResponse.Size(m)
}
func (m *PropertyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyResponse proto.InternalMessageInfo

func (m *PropertyResponse) GetProperty() *Property {
	if m != nil {
		return m.Property
	}
	return nil
}

type PropertiesResponse struct {
	Properties           []*Property `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	Position             uint32      `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Total                uint32      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PropertiesResponse) Reset()         { *m = PropertiesResponse{} }
func (m *PropertiesResponse) String() string { return proto.CompactTextString(m) }
func (*PropertiesResponse) ProtoMessage()    {}
func (*PropertiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c191a4a5f523572b, []int{5}
}

func (m *PropertiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertiesResponse.Unmarshal(m, b)
}
func (m *PropertiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertiesResponse.Marshal(b, m, deterministic)
}
func (m *PropertiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertiesResponse.Merge(m, src)
}
func (m *PropertiesResponse) XXX_Size() int {
	return xxx_messageInfo_PropertiesResponse.Size(m)
}
func (m *PropertiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PropertiesResponse proto.InternalMessageInfo

func (m *PropertiesResponse) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *PropertiesResponse) GetPosition() uint32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *PropertiesResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Property)(nil), "v1.Property")
	proto.RegisterType((*PropertyValue)(nil), "v1.PropertyValue")
	proto.RegisterType((*PropertyRequest)(nil), "v1.PropertyRequest")
	proto.RegisterType((*PropertiesRequest)(nil), "v1.PropertiesRequest")
	proto.RegisterType((*PropertyResponse)(nil), "v1.PropertyResponse")
	proto.RegisterType((*PropertiesResponse)(nil), "v1.PropertiesResponse")
}

func init() {
	proto.RegisterFile("property.proto", fileDescriptor_c191a4a5f523572b)
}

var fileDescriptor_c191a4a5f523572b = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x93, 0x36, 0xb1, 0xc7, 0x24, 0xd0, 0xa5, 0xc0, 0xca, 0x45, 0xaa, 0xf1, 0xc9, 0x48,
	0x28, 0x55, 0x83, 0x38, 0xc1, 0x1f, 0xe0, 0x86, 0x5c, 0x89, 0x6b, 0xe4, 0xc6, 0x43, 0xb4, 0x92,
	0xd3, 0xdd, 0xee, 0xae, 0x2d, 0xa5, 0x77, 0x7e, 0x04, 0x67, 0xfe, 0x28, 0xda, 0xaf, 0xd8, 0xe9,
	0x81, 0x93, 0xf7, 0xbd, 0x79, 0xeb, 0x99, 0xf7, 0xc6, 0x86, 0xa5, 0x90, 0x5c, 0xa0, 0xd4, 0x87,
	0x95, 0x90, 0x5c, 0x73, 0x32, 0xe9, 0x6f, 0xb3, 0xab, 0x1d, 0xe7, 0xbb, 0x16, 0x6f, 0x2c, 0x73,
	0xdf, 0xfd, 0xba, 0xc1, 0xbd, 0x08, 0x82, 0x6c, 0xb9, 0xad, 0x35, 0xee, 0xb8, 0xf4, 0xb8, 0xf8,
	0x3b, 0x81, 0xf8, 0x87, 0x7f, 0x07, 0x59, 0xc2, 0x84, 0x35, 0x34, 0xca, 0xa3, 0x32, 0xa9, 0x26,
	0xac, 0x21, 0xef, 0x60, 0xde, 0x29, 0x94, 0x1b, 0xd6, 0xd0, 0x49, 0x1e, 0x95, 0x8b, 0x6a, 0x66,
	0xe0, 0xf7, 0x86, 0x5c, 0xc2, 0xb9, 0x66, 0xba, 0x45, 0x3a, 0xb5, 0x5a, 0x07, 0x08, 0x81, 0xb3,
	0x2d, 0x6f, 0x90, 0x9e, 0x59, 0xd2, 0x9e, 0x0d, 0xa7, 0x0f, 0x02, 0xe9, 0xb9, 0xbd, 0x6f, 0xcf,
	0x84, 0xc2, 0xbc, 0x61, 0x4a, 0xb4, 0xf5, 0x81, 0xce, 0x2c, 0x1d, 0x20, 0xc9, 0x20, 0x96, 0xf8,
	0xd8, 0x31, 0x89, 0x0d, 0x9d, 0xe7, 0x51, 0x19, 0x57, 0x47, 0x6c, 0x6a, 0xfb, 0xae, 0xd5, 0x4c,
	0xb4, 0x48, 0x63, 0x57, 0x0b, 0xd8, 0x74, 0x51, 0x5c, 0x6a, 0x9a, 0xb8, 0x2e, 0xe6, 0x4c, 0x3e,
	0xc2, 0xac, 0xaf, 0xdb, 0x0e, 0x15, 0x85, 0x7c, 0x5a, 0xa6, 0xeb, 0x8b, 0x55, 0x7f, 0xbb, 0x0a,
	0x56, 0x7f, 0x9a, 0x4a, 0xe5, 0x05, 0xe4, 0x1a, 0x52, 0xa6, 0x71, 0xbf, 0xf1, 0xfa, 0x34, 0x9f,
	0x96, 0x8b, 0x0a, 0x0c, 0x65, 0x75, 0xaa, 0xf8, 0x13, 0xc1, 0xe2, 0xe4, 0xea, 0x28, 0xaa, 0xc5,
	0xff, 0xa3, 0xba, 0x86, 0x34, 0xec, 0xc8, 0x14, 0xa7, 0xb6, 0x08, 0x81, 0x72, 0x59, 0xda, 0xbe,
	0x3e, 0x36, 0x07, 0x0c, 0xcb, 0xf6, 0xf5, 0xce, 0x05, 0x97, 0x54, 0x0e, 0x1c, 0x7d, 0xce, 0x06,
	0x9f, 0xc5, 0x07, 0x78, 0x19, 0x46, 0xab, 0xf0, 0xb1, 0x43, 0xa5, 0x9f, 0x0f, 0x57, 0xf4, 0x70,
	0xe1, 0x25, 0x0c, 0x55, 0x10, 0x11, 0x38, 0x13, 0xa6, 0x81, 0x93, 0xd9, 0x33, 0xb9, 0x82, 0xc4,
	0x3c, 0x37, 0x8a, 0x3d, 0xa1, 0xf7, 0x11, 0x1b, 0xe2, 0x8e, 0x3d, 0x0d, 0xcd, 0xdd, 0xce, 0x5d,
	0xc8, 0xef, 0x21, 0x69, 0x98, 0xc4, 0xad, 0x66, 0xfc, 0xc1, 0x1b, 0x18, 0x88, 0xe2, 0x1b, 0xbc,
	0x1a, 0x46, 0x53, 0x82, 0x3f, 0x28, 0x24, 0x25, 0xc4, 0xc1, 0xbc, 0x6d, 0x9d, 0xae, 0x5f, 0x8c,
	0x17, 0x53, 0x1d, 0xab, 0x85, 0x06, 0x32, 0x9e, 0xda, 0xdf, 0xff, 0x04, 0x21, 0x3c, 0x86, 0x8a,
	0x46, 0x76, 0xb5, 0xa7, 0x6f, 0x18, 0xd5, 0xcd, 0x47, 0x23, 0xb8, 0x62, 0x76, 0xbc, 0xe0, 0xc7,
	0x63, 0xfb, 0x11, 0x73, 0x5d, 0xb7, 0x7e, 0x27, 0x0e, 0xac, 0x7f, 0x47, 0x43, 0x9e, 0x77, 0x28,
	0x7b, 0xb6, 0x45, 0xf2, 0x65, 0xf4, 0x8f, 0xbc, 0x3e, 0xe9, 0xe5, 0xb2, 0xcc, 0x2e, 0x4f, 0x49,
	0x3f, 0xea, 0x57, 0x80, 0xc1, 0x00, 0x79, 0x33, 0xd2, 0x0c, 0x6b, 0xc8, 0xde, 0x3e, 0xa7, 0xdd,
	0xe5, 0xfb, 0x99, 0xfd, 0x3f, 0x3f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x48, 0x4e, 0x87,
	0xe2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PropertyServiceClient is the client API for PropertyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PropertyServiceClient interface {
	Property(ctx context.Context, in *PropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	Properties(ctx context.Context, in *PropertiesRequest, opts ...grpc.CallOption) (*PropertiesResponse, error)
}

type propertyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyServiceClient(cc grpc.ClientConnInterface) PropertyServiceClient {
	return &propertyServiceClient{cc}
}

func (c *propertyServiceClient) Property(ctx context.Context, in *PropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, "/v1.PropertyService/Property", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) Properties(ctx context.Context, in *PropertiesRequest, opts ...grpc.CallOption) (*PropertiesResponse, error) {
	out := new(PropertiesResponse)
	err := c.cc.Invoke(ctx, "/v1.PropertyService/Properties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyServiceServer is the server API for PropertyService service.
type PropertyServiceServer interface {
	Property(context.Context, *PropertyRequest) (*PropertyResponse, error)
	Properties(context.Context, *PropertiesRequest) (*PropertiesResponse, error)
}

// UnimplementedPropertyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPropertyServiceServer struct {
}

func (*UnimplementedPropertyServiceServer) Property(ctx context.Context, req *PropertyRequest) (*PropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Property not implemented")
}
func (*UnimplementedPropertyServiceServer) Properties(ctx context.Context, req *PropertiesRequest) (*PropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Properties not implemented")
}

func RegisterPropertyServiceServer(s *grpc.Server, srv PropertyServiceServer) {
	s.RegisterService(&_PropertyService_serviceDesc, srv)
}

func _PropertyService_Property_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).Property(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PropertyService/Property",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).Property(ctx, req.(*PropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_Properties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).Properties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PropertyService/Properties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).Properties(ctx, req.(*PropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PropertyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PropertyService",
	HandlerType: (*PropertyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Property",
			Handler:    _PropertyService_Property_Handler,
		},
		{
			MethodName: "Properties",
			Handler:    _PropertyService_Properties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "property.proto",
}
