// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname             string   `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Photo                string   `protobuf:"bytes,5,opt,name=photo,proto3" json:"photo,omitempty"`
	Role                 uint32   `protobuf:"varint,6,opt,name=role,proto3" json:"role,omitempty"`
	Trademark            string   `protobuf:"bytes,7,opt,name=trademark,proto3" json:"trademark,omitempty"`
	Tariff               uint32   `protobuf:"varint,8,opt,name=tariff,proto3" json:"tariff,omitempty"`
	Amount               float32  `protobuf:"fixed32,9,opt,name=amount,proto3" json:"amount,omitempty"`
	About                string   `protobuf:"bytes,10,opt,name=about,proto3" json:"about,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *User) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *User) GetTrademark() string {
	if m != nil {
		return m.Trademark
	}
	return ""
}

func (m *User) GetTariff() uint32 {
	if m != nil {
		return m.Tariff
	}
	return 0
}

func (m *User) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *User) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

type RegisterRequest struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type IsProfileCompleteResponse struct {
	Complete             bool     `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsProfileCompleteResponse) Reset()         { *m = IsProfileCompleteResponse{} }
func (m *IsProfileCompleteResponse) String() string { return proto.CompactTextString(m) }
func (*IsProfileCompleteResponse) ProtoMessage()    {}
func (*IsProfileCompleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *IsProfileCompleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsProfileCompleteResponse.Unmarshal(m, b)
}
func (m *IsProfileCompleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsProfileCompleteResponse.Marshal(b, m, deterministic)
}
func (m *IsProfileCompleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsProfileCompleteResponse.Merge(m, src)
}
func (m *IsProfileCompleteResponse) XXX_Size() int {
	return xxx_messageInfo_IsProfileCompleteResponse.Size(m)
}
func (m *IsProfileCompleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsProfileCompleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsProfileCompleteResponse proto.InternalMessageInfo

func (m *IsProfileCompleteResponse) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

type UserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*RegisterRequest)(nil), "v1.RegisterRequest")
	proto.RegisterType((*AuthRequest)(nil), "v1.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "v1.AuthResponse")
	proto.RegisterType((*IsProfileCompleteResponse)(nil), "v1.IsProfileCompleteResponse")
	proto.RegisterType((*UserResponse)(nil), "v1.UserResponse")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x8d, 0x13, 0x9c, 0x9b, 0x42, 0xd1, 0x50, 0x55, 0x83, 0x61, 0x11, 0x79, 0x15, 0x24,
	0xe4, 0x2a, 0x65, 0xc1, 0x12, 0x01, 0x62, 0xc1, 0x02, 0x09, 0x19, 0xf1, 0x01, 0x93, 0xe6, 0x3a,
	0x1d, 0x75, 0xec, 0x6b, 0xe6, 0x11, 0xc4, 0xb7, 0xf0, 0x8b, 0x7c, 0x04, 0x9a, 0x19, 0xc7, 0x25,
	0xc9, 0xa6, 0x3b, 0x9f, 0x33, 0xc7, 0xe7, 0xdc, 0x17, 0x80, 0x33, 0xa8, 0xab, 0x5e, 0x93, 0x25,
	0x96, 0xee, 0x56, 0xc5, 0xcb, 0x2d, 0xd1, 0x56, 0xe1, 0x55, 0x60, 0xd6, 0xae, 0xb9, 0xc2, 0xb6,
	0xb7, 0xbf, 0xa3, 0xa0, 0xfc, 0x9b, 0x40, 0xf6, 0xc3, 0xa0, 0x66, 0x4f, 0x21, 0x95, 0x1b, 0x9e,
	0x2c, 0x92, 0xe5, 0x93, 0x3a, 0x95, 0x1b, 0x56, 0x40, 0xde, 0x38, 0xa5, 0x3a, 0xd1, 0x22, 0x4f,
	0x17, 0xc9, 0x72, 0x56, 0x8f, 0x98, 0x5d, 0xc0, 0xa4, 0xbf, 0xa5, 0x0e, 0xf9, 0xa3, 0xf0, 0x10,
	0x81, 0x67, 0xb1, 0x15, 0x52, 0xf1, 0x2c, 0xb2, 0x01, 0x0c, 0x5a, 0x4b, 0x7c, 0x32, 0x6a, 0x2d,
	0x31, 0x06, 0x99, 0x26, 0x85, 0x7c, 0x1a, 0xf2, 0xc2, 0x37, 0x7b, 0x05, 0x33, 0xab, 0xc5, 0x06,
	0x5b, 0xa1, 0xef, 0xf8, 0xe3, 0xa0, 0xbe, 0x27, 0xd8, 0x25, 0x4c, 0xad, 0xd0, 0xb2, 0x69, 0x78,
	0x1e, 0xfe, 0x19, 0x90, 0xe7, 0x45, 0x4b, 0xae, 0xb3, 0x7c, 0xb6, 0x48, 0x96, 0x69, 0x3d, 0x20,
	0x9f, 0x2b, 0xd6, 0xe4, 0x2c, 0x87, 0x98, 0x1b, 0x40, 0xe9, 0xe0, 0xbc, 0xc6, 0xad, 0x34, 0x16,
	0x75, 0x8d, 0x3f, 0x1d, 0x1a, 0x7b, 0xd0, 0x68, 0x72, 0xda, 0x68, 0x6c, 0x29, 0x3d, 0x6d, 0xe9,
	0xb8, 0xfd, 0x02, 0xf2, 0x5e, 0x18, 0xf3, 0x8b, 0xf4, 0x66, 0x98, 0xc0, 0x88, 0xcb, 0xf7, 0x30,
	0xff, 0xe0, 0xec, 0xed, 0x3e, 0xf2, 0x02, 0x26, 0x8a, 0xb6, 0xb2, 0x1b, 0xf2, 0x22, 0x38, 0x30,
	0x48, 0x8f, 0x0c, 0x3e, 0xc2, 0x59, 0x34, 0x30, 0x3d, 0x75, 0xc6, 0xcf, 0x2a, 0xf3, 0x5b, 0x0e,
	0x06, 0xf3, 0xeb, 0xbc, 0xda, 0xad, 0x2a, 0xbf, 0xc5, 0x3a, 0xb0, 0xde, 0xdf, 0xd2, 0x1d, 0x76,
	0xfb, 0xb2, 0x03, 0x28, 0xdf, 0xc1, 0x8b, 0x2f, 0xe6, 0x9b, 0xa6, 0x46, 0x2a, 0xfc, 0x44, 0x6d,
	0xaf, 0xd0, 0xe2, 0x68, 0x58, 0x40, 0x7e, 0x33, 0x70, 0xc1, 0x34, 0xaf, 0x47, 0x5c, 0xbe, 0x81,
	0xb3, 0x60, 0xfe, 0xa0, 0xf0, 0xeb, 0x3f, 0x09, 0xcc, 0x3d, 0xfc, 0x8e, 0x7a, 0x27, 0x6f, 0x90,
	0xbd, 0x86, 0xcc, 0x97, 0xce, 0xce, 0xbd, 0xee, 0xbf, 0x29, 0x14, 0xcf, 0xee, 0x89, 0xc1, 0xb8,
	0x82, 0xf4, 0x2b, 0xb2, 0xcb, 0x2a, 0x1e, 0x6c, 0xb5, 0x3f, 0xd8, 0xea, 0xb3, 0x3f, 0xd8, 0xa8,
	0x3f, 0x28, 0x64, 0x05, 0xf9, 0x7e, 0x9b, 0xec, 0xb9, 0x7f, 0x3d, 0xda, 0xed, 0x69, 0xc4, 0x7a,
	0x1a, 0x4c, 0xdf, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xe2, 0x54, 0x2a, 0x25, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Me(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/v1.UserService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Me(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/v1.UserService/Me", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/v1.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	Me(context.Context, *empty.Empty) (*UserResponse, error)
	Register(context.Context, *RegisterRequest) (*AuthResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Auth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedUserServiceServer) Me(ctx context.Context, req *empty.Empty) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Me not implemented")
}
func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Me_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Me(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/Me",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Me(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _UserService_Auth_Handler,
		},
		{
			MethodName: "Me",
			Handler:    _UserService_Me_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
