// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vendor.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vendor struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vendor) Reset()         { *m = Vendor{} }
func (m *Vendor) String() string { return proto.CompactTextString(m) }
func (*Vendor) ProtoMessage()    {}
func (*Vendor) Descriptor() ([]byte, []int) {
	return fileDescriptor_f466d14b0fac1564, []int{0}
}

func (m *Vendor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vendor.Unmarshal(m, b)
}
func (m *Vendor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vendor.Marshal(b, m, deterministic)
}
func (m *Vendor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vendor.Merge(m, src)
}
func (m *Vendor) XXX_Size() int {
	return xxx_messageInfo_Vendor.Size(m)
}
func (m *Vendor) XXX_DiscardUnknown() {
	xxx_messageInfo_Vendor.DiscardUnknown(m)
}

var xxx_messageInfo_Vendor proto.InternalMessageInfo

func (m *Vendor) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Vendor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vendor) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type VendorRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VendorRequest) Reset()         { *m = VendorRequest{} }
func (m *VendorRequest) String() string { return proto.CompactTextString(m) }
func (*VendorRequest) ProtoMessage()    {}
func (*VendorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f466d14b0fac1564, []int{1}
}

func (m *VendorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorRequest.Unmarshal(m, b)
}
func (m *VendorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorRequest.Marshal(b, m, deterministic)
}
func (m *VendorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorRequest.Merge(m, src)
}
func (m *VendorRequest) XXX_Size() int {
	return xxx_messageInfo_VendorRequest.Size(m)
}
func (m *VendorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VendorRequest proto.InternalMessageInfo

func (m *VendorRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type VendorsRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction            string   `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VendorsRequest) Reset()         { *m = VendorsRequest{} }
func (m *VendorsRequest) String() string { return proto.CompactTextString(m) }
func (*VendorsRequest) ProtoMessage()    {}
func (*VendorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f466d14b0fac1564, []int{2}
}

func (m *VendorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorsRequest.Unmarshal(m, b)
}
func (m *VendorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorsRequest.Marshal(b, m, deterministic)
}
func (m *VendorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorsRequest.Merge(m, src)
}
func (m *VendorsRequest) XXX_Size() int {
	return xxx_messageInfo_VendorsRequest.Size(m)
}
func (m *VendorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VendorsRequest proto.InternalMessageInfo

func (m *VendorsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *VendorsRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *VendorsRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *VendorsRequest) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

type VendorResponse struct {
	Vendor               *Vendor  `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VendorResponse) Reset()         { *m = VendorResponse{} }
func (m *VendorResponse) String() string { return proto.CompactTextString(m) }
func (*VendorResponse) ProtoMessage()    {}
func (*VendorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f466d14b0fac1564, []int{3}
}

func (m *VendorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorResponse.Unmarshal(m, b)
}
func (m *VendorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorResponse.Marshal(b, m, deterministic)
}
func (m *VendorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorResponse.Merge(m, src)
}
func (m *VendorResponse) XXX_Size() int {
	return xxx_messageInfo_VendorResponse.Size(m)
}
func (m *VendorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VendorResponse proto.InternalMessageInfo

func (m *VendorResponse) GetVendor() *Vendor {
	if m != nil {
		return m.Vendor
	}
	return nil
}

type VendorsResponse struct {
	Vendors              []*Vendor `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
	Total                uint32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VendorsResponse) Reset()         { *m = VendorsResponse{} }
func (m *VendorsResponse) String() string { return proto.CompactTextString(m) }
func (*VendorsResponse) ProtoMessage()    {}
func (*VendorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f466d14b0fac1564, []int{4}
}

func (m *VendorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorsResponse.Unmarshal(m, b)
}
func (m *VendorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorsResponse.Marshal(b, m, deterministic)
}
func (m *VendorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorsResponse.Merge(m, src)
}
func (m *VendorsResponse) XXX_Size() int {
	return xxx_messageInfo_VendorsResponse.Size(m)
}
func (m *VendorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VendorsResponse proto.InternalMessageInfo

func (m *VendorsResponse) GetVendors() []*Vendor {
	if m != nil {
		return m.Vendors
	}
	return nil
}

func (m *VendorsResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Vendor)(nil), "v1.Vendor")
	proto.RegisterType((*VendorRequest)(nil), "v1.VendorRequest")
	proto.RegisterType((*VendorsRequest)(nil), "v1.VendorsRequest")
	proto.RegisterType((*VendorResponse)(nil), "v1.VendorResponse")
	proto.RegisterType((*VendorsResponse)(nil), "v1.VendorsResponse")
}

func init() {
	proto.RegisterFile("vendor.proto", fileDescriptor_f466d14b0fac1564)
}

var fileDescriptor_f466d14b0fac1564 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x0d, 0xb4, 0x16, 0x19, 0xa5, 0xc6, 0xd1, 0xc3, 0xa6, 0x9a, 0x48, 0x36, 0x1e, 0x7a, 0xc2,
	0x14, 0xfd, 0x0d, 0xde, 0xbc, 0xd0, 0xc4, 0xab, 0x41, 0x98, 0x98, 0x4d, 0x94, 0xc5, 0xdd, 0x2d,
	0x89, 0xfd, 0xf5, 0x86, 0xfd, 0xa8, 0xd8, 0x13, 0xb3, 0xef, 0x63, 0xde, 0xe4, 0x01, 0xe7, 0x03,
	0x75, 0xad, 0x54, 0x45, 0xaf, 0xa4, 0x91, 0x18, 0x0f, 0x1b, 0xfe, 0x0c, 0x8b, 0x57, 0x8b, 0xe1,
	0x12, 0x62, 0xd1, 0xb2, 0x28, 0x8f, 0xd6, 0x59, 0x15, 0x8b, 0x16, 0x11, 0xe6, 0x5d, 0xfd, 0x45,
	0x2c, 0xce, 0xa3, 0x75, 0x5a, 0xd9, 0x19, 0x19, 0x24, 0x8d, 0xdc, 0x75, 0x46, 0xfd, 0xb0, 0x99,
	0x85, 0xc3, 0x93, 0xdf, 0x41, 0xe6, 0xf6, 0x54, 0xf4, 0xbd, 0x23, 0x6d, 0x8e, 0xd7, 0x71, 0x0d,
	0x4b, 0x27, 0xd0, 0x41, 0x81, 0x30, 0xef, 0xeb, 0x0f, 0xf2, 0x1a, 0x3b, 0xe3, 0x0d, 0xa4, 0xe3,
	0xf7, 0x4d, 0x8b, 0xbd, 0x4b, 0xce, 0xaa, 0xd3, 0x11, 0xd8, 0x8a, 0x3d, 0x8d, 0x06, 0x2d, 0x95,
	0xf1, 0xd1, 0x76, 0xc6, 0x5b, 0x48, 0x5b, 0xa1, 0xa8, 0x31, 0x42, 0x76, 0x6c, 0x6e, 0x89, 0x3f,
	0x80, 0x3f, 0x85, 0xd0, 0x8a, 0x74, 0x2f, 0x3b, 0x4d, 0xc8, 0x61, 0xe1, 0x3a, 0xb0, 0xb1, 0x67,
	0x25, 0x14, 0xc3, 0xa6, 0xf0, 0x1a, 0xcf, 0xf0, 0x17, 0xb8, 0x38, 0x9c, 0xea, 0x6d, 0xf7, 0x90,
	0x38, 0x52, 0xb3, 0x28, 0x9f, 0x1d, 0xf9, 0x02, 0x85, 0xd7, 0x70, 0x62, 0xa4, 0xa9, 0x3f, 0xfd,
	0xe5, 0xee, 0x51, 0x9a, 0x50, 0xcd, 0x96, 0xd4, 0x20, 0x1a, 0xc2, 0x87, 0x43, 0xe7, 0x97, 0x93,
	0x2d, 0xae, 0x95, 0x15, 0x4e, 0x21, 0x9f, 0x5e, 0x42, 0xe2, 0x0f, 0xc2, 0x09, 0x1d, 0x8a, 0x5c,
	0x5d, 0xfd, 0xc3, 0x9c, 0xe7, 0x7d, 0x61, 0xff, 0xf1, 0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x45, 0x4a, 0x7b, 0x01, 0xf3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VendorServiceClient is the client API for VendorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VendorServiceClient interface {
	Vendor(ctx context.Context, in *VendorRequest, opts ...grpc.CallOption) (*VendorResponse, error)
	Vendors(ctx context.Context, in *VendorsRequest, opts ...grpc.CallOption) (*VendorsResponse, error)
}

type vendorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVendorServiceClient(cc grpc.ClientConnInterface) VendorServiceClient {
	return &vendorServiceClient{cc}
}

func (c *vendorServiceClient) Vendor(ctx context.Context, in *VendorRequest, opts ...grpc.CallOption) (*VendorResponse, error) {
	out := new(VendorResponse)
	err := c.cc.Invoke(ctx, "/v1.VendorService/Vendor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorServiceClient) Vendors(ctx context.Context, in *VendorsRequest, opts ...grpc.CallOption) (*VendorsResponse, error) {
	out := new(VendorsResponse)
	err := c.cc.Invoke(ctx, "/v1.VendorService/Vendors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VendorServiceServer is the server API for VendorService service.
type VendorServiceServer interface {
	Vendor(context.Context, *VendorRequest) (*VendorResponse, error)
	Vendors(context.Context, *VendorsRequest) (*VendorsResponse, error)
}

// UnimplementedVendorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVendorServiceServer struct {
}

func (*UnimplementedVendorServiceServer) Vendor(ctx context.Context, req *VendorRequest) (*VendorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vendor not implemented")
}
func (*UnimplementedVendorServiceServer) Vendors(ctx context.Context, req *VendorsRequest) (*VendorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vendors not implemented")
}

func RegisterVendorServiceServer(s *grpc.Server, srv VendorServiceServer) {
	s.RegisterService(&_VendorService_serviceDesc, srv)
}

func _VendorService_Vendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).Vendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VendorService/Vendor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).Vendor(ctx, req.(*VendorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendorService_Vendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServiceServer).Vendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VendorService/Vendors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServiceServer).Vendors(ctx, req.(*VendorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VendorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VendorService",
	HandlerType: (*VendorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vendor",
			Handler:    _VendorService_Vendor_Handler,
		},
		{
			MethodName: "Vendors",
			Handler:    _VendorService_Vendors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vendor.proto",
}
